// MobileGL - MobileGL/MG_Pipe/MGPipe.h
// Copyright (c) 2025-2026 MobileGL-Dev
// Licensed under the GNU Lesser General Public License v3.0:
//   https://www.gnu.org/licenses/gpl-3.0.txt
//   https://www.gnu.org/licenses/lgpl-3.0.txt
// SPDX-License-Identifier: LGPL-3.0-only
// End of Source File Header

#pragma once
#include <Includes.h>

#include "MGPipeCallbacks.h"
#include "MGPipeHandles.h"
#include "MGPipeHostSpan.h"
#include "MGPipeTypes.h"

// The MGPipe boundary (plan B section 4).
//
// The two interface tables are FUNCTION-POINTER STRUCTS, not virtual bases. Three reasons
// out of this repository rather than out of gallium: the boundary already is a
// function-pointer struct sitting on one hook point in MG_Backend/Init.cpp; a nullptr entry
// already means "not implemented, frontend falls back", which is exactly what a
// not-yet-migrated subsystem needs to say while it keeps pulling; and MG_Test already
// substitutes this table to mock a backend. The rare EGL and caps surface stays on
// pActiveBackendObject's virtual functions.
namespace MobileGL::MG_Pipe {
    // Unscoped on purpose: PipeCalls.def spells these as bare tokens so the same file can
    // be read by the C++ preprocessor and by scripts/gen_pipe.py.
    enum MGPipeCallClass : Uint8 {
        kScreen,
        kCtxCso,
        kCtxState,
        kCtxObject,
        kCtxVerb,
        kCtxQuery,
        kCallClassCount,
    };

    enum MGPipeCallFlags : Uint32 {
        kNone = 0,
        // The caller must not proceed until the server has acknowledged. Rare by design.
        kNeedsAck = 1u << 0,
        // Carries an MGPBlobRef.
        kHasBlob = 1u << 1,
        // Carries a variable-length array after the fixed payload.
        kVarTail = 1u << 2,
        // Carries an MGHostSpan - the one shape that changes with the transport.
        kHostSpan = 1u << 3,
        // Answers into an MGPReplySlot; never blocks.
        kReplySlot = 1u << 4,
        // May be null in a backend's table. A null entry is a real answer ("this backend
        // does not implement it"), not an error: DirectVulkan deliberately leaves
        // buffer_subdata_resident unregistered, and SetSwapInterval likewise.
        kOptional = 1u << 5,
    };

    // The pipeline/dynamic split of RenderStateParameters, defined exactly once (section
    // 4.5.2). Generated by G7 from the field list ComputePipelineStateHash already hashes;
    // MGPipeRenderStateSpans.cpp and the setter-consistency test land with P2, which is
    // when the chunk table can be filled with real offsets.
    struct MGPipeRenderStateSpans;

    // The catalogue itself. Only macros, so it is safe to expand inside the namespace, and
    // consumers (the unit test, later the transport) get MGP_CALL_LIST from this header.
#include "PipeCalls.def"

    // G1: the two interface tables. A null entry means "not implemented" (section 4.1).
#include "generated/PipeTables.inc"

    // The installed tables. Zero-initialized, so an un-installed MGPipe is every entry
    // null - which is precisely the pre-migration state.
    inline MGPipeScreen gMGPipeScreen{};
    inline MGPipeContext gMGPipeContext{};

    // G2: monolith thunks. These are what MG_Impl call sites move onto, replacing
    // gBackendFunctionsTable.GL.* one name at a time.
#include "generated/PipeThunks.inc"

    // G3: wire records, their size assertions, and the applier's bounds precondition.
#include "generated/PipeWire.inc"

    // G4: the MOBILEGL_PIPE_VERIFY field-wise comparators.
#include "generated/PipeVerify.inc"

    // G5: PipeInputs field ids and the per-verb poison generations.
#include "generated/PipeFilled.inc"

    // G5b: the verb enum (one per GLFunctionsTable entry), the verb classes and their
    // may-read field masks - what MGPipeFillForVerb fills and what a poison build lets a
    // verb read (FillPoints.def).
#include "generated/PipeFillPoints.inc"

    // G6: the backend read inventory's coverage table.
#include "generated/PipeCoverage.inc"

    // G7: the render-state pipeline subset, by member name.
#include "generated/PipeSpanTable.inc"
} // namespace MobileGL::MG_Pipe
