// MobileGL - MobileGL/MG_Pipe/MGPipeTypes.h
// Copyright (c) 2025-2026 MobileGL-Dev
// Licensed under the GNU Lesser General Public License v3.0:
//   https://www.gnu.org/licenses/gpl-3.0.txt
//   https://www.gnu.org/licenses/lgpl-3.0.txt
// SPDX-License-Identifier: LGPL-3.0-only
// End of Source File Header

#pragma once
#include <Includes.h>

#include "MGPipeHandles.h"
#include "MGPipeHostSpan.h"

// Every MGPipe payload (plan B section 4.5). Each one is a flat POD with explicit padding,
// carries a static_assert on trivial copyability and one on its exact size, and never
// contains a pointer: MGHostSpan, the one shape that changes with the transport, only ever
// rides in a variable tail (draw_vbo's user indices, set_shader_buffers' named-UBO bytes),
// never inline in a fixed payload.
//
// Sizes are asserted rather than merely documented because the wire records generated from
// these structs (generated/PipeWire.inc) are memcpy'd; a field silently changing width is a
// protocol break that no test would otherwise see.
//
// P0.5 DEBT, recorded here so it is impossible to miss: two payloads reach into headers
// this directory is eventually forbidden to see - MGPCaps embeds MG_Backend's
// DynamicBackendParameters, and ResidualValueBlock embeds MG_State's RenderStateParameters
// and PixelStoreParameters. Both are deliberate: the caps block IS that struct (section
// 4.4.1) and the residual block is the migration carrier for Track V (section 6.3). P0.5
// extracts MGPipeValueTypes.h and both includes below go away; until then purity gate A
// (section 10.3) cannot be armed for this header.
#include <MG_Backend/BackendObject.h>
#include <MG_State/GLState/RenderState/RenderState.h>

namespace MobileGL::MG_Pipe {
    using MG_Backend::DynamicBackendParameters;
    // Both live directly in namespace MobileGL today; P0.5 moves them into
    // MG_Pipe/MGPipeValueTypes.h.
    using MobileGL::PixelStoreParameters;
    using MobileGL::RenderStateParameters;

    // A payload must be memcpy-able and its size must be an exact, stated number.
#define MGP_ASSERT_POD(T, Size)                                                                                        \
    static_assert(std::is_trivially_copyable_v<T>, #T " must be trivially copyable");                                  \
    static_assert(sizeof(T) == (Size), #T " changed size; update the wire format and this assertion")

    // ---------------------------------------------------------------------------------
    // Shared primitives
    // ---------------------------------------------------------------------------------

    // A run of bytes in the command stream's blob area. Monolith: Seg is
    // kMGHostSpanSegNone and Offset is an address into the caller's staging arena. Split:
    // Seg names a transport segment.
    struct MGPBlobRef {
        Uint64 Offset;
        Uint64 Size;
        Uint32 Seg;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPBlobRef, 24);

    struct MGPRange {
        Uint64 Offset;
        Uint64 Size;
    };
    MGP_ASSERT_POD(MGPRange, 16);

    // Destination box in the level's own coordinate system (section 4.5.6).
    struct MGPBox {
        Int32 X, Y, Z;
        Uint32 W, H, D;
    };
    MGP_ASSERT_POD(MGPBox, 24);

    // Where an asynchronous answer lands. Every server query in this catalogue is
    // async-with-handle; none of them blocks (section 4.4.6, "the total rule").
    struct MGPReplySlot {
        Uint64 Id;
    };
    MGP_ASSERT_POD(MGPReplySlot, 8);

    // One contiguous run of RenderStateParameters bytes. The pipeline/dynamic split is
    // defined exactly once, in MGPipeRenderStateSpans, and generated by G7 from the field
    // list VulkanRenderer::ComputePipelineStateHash already hashes (section 4.5.2).
    struct MGPStateChunk {
        Uint16 Offset;
        Uint16 Length;
    };
    MGP_ASSERT_POD(MGPStateChunk, 4);

    // The payload of every call that carries nothing but an object identity.
    struct MGPHandleOnly {
        MGPipeHandle Handle;
        Uint32 Kind; // MGPipeKind, widened for a stable wire size
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPHandleOnly, 16);

    // ---------------------------------------------------------------------------------
    // Screen: caps, resources, fences
    // ---------------------------------------------------------------------------------

    // Capability bits that replace "is this table slot null" as an implicit feature probe
    // (section 4.4.1). The five ownership-switch bits of v1 are deliberately absent: what
    // they tried to express - who performs primitive-restart rewriting and multi-draw
    // flattening - is not expressible as a capability (D-B7).
    enum MGPCapBit : Uint64 {
        kCapNone = 0,
        kCapViewportArray = 1ull << 0,
        kCapFloat64VertexAttrib = 1ull << 1,
        kCapResidentSubData = 1ull << 2,
        kCapCpuXfbPrimitiveAccounting = 1ull << 3,
        kCapTimerQuery = 1ull << 4,
        kCapOcclusionQuery = 1ull << 5,
        kCapXfbPrimitivesQuery = 1ull << 6,
        // The server rewrites restart indices / flattens multi-draws itself and therefore
        // needs the index bytes on its side: under split this arms the index host mirror
        // (D-B7).
        kCapNeedsHostIndexBytes = 1ull << 7,
        // The server packs named uniform blocks into its own ring and therefore needs the
        // host bytes of a set_shader_buffers(Uniform) range (D-B8).
        kCapNeedsHostUboBytes = 1ull << 8,
    };

    struct MGPCaps {
        // The ~90 flat scalars the backends already publish, by inclusion rather than by
        // restatement: a caps field added there must not need a second edit here. This is
        // also where the six per-axis compute limits (MaxComputeWorkGroupCount/Size) ride -
        // the only indexed answers the device owns, and therefore the only ones that outlive
        // the GetIntegeri_v table entry (see the PipeCalls.def footer).
        DynamicBackendParameters Dynamic;
        Uint64 CallMask; // MGPCapBit
        // The two halves that are not flat PODs travel as blobs: the format capability
        // cache holds Vector<Int> sample-count lists, and the renderer strings are
        // Strings. Their serializers land with the transport (P5).
        MGPBlobRef FormatCapabilities;
        MGPBlobRef RendererInfo;
    };
    static_assert(std::is_trivially_copyable_v<MGPCaps>, "MGPCaps must be trivially copyable");
    // Stated as a COMPOSITION rather than a literal: DynamicBackendParameters still carries
    // SizeT fields, so its literal size is ABI-dependent until P0.5 moves the caps block
    // into MGPipeValueTypes.h with fixed-width members. The assertion still fires on any
    // padding introduced between the members below.
    static_assert(sizeof(MGPCaps) == sizeof(DynamicBackendParameters) + 8 + 24 + 24,
                  "MGPCaps gained padding or a member; update the wire format");

    // Discriminated resource descriptor: buffers, every texture target and renderbuffers
    // share one create/respecify shape (section 4.5.1).
    struct MGPResourceDesc {
        MGPipeHandle Resource;
        Uint8 Target;      // Buffer | Tex1D..TexCubeArray | Tex2DMS.. | Renderbuffer | TexBuffer
        Uint8 StorageKind; // == TextureStorageType (Mipmap | Buffer)
        // VERTEX|INDEX|CONSTANT|SHADER_BUFFER|INDIRECT|SAMPLER|SHADER_IMAGE|RENDER_TARGET|
        // DEPTH_STENCIL|STREAM_OUTPUT|ATOMIC|ELEMENT_ARRAY. The ELEMENT_ARRAY bit is the
        // D-B7 switch: with kCapNeedsHostIndexBytes set the server mirrors this resource.
        Uint16 BindMask;
        Uint32 InternalFormat; // already resolved to an uncompressed fallback by the client
        Uint32 Width, Height, Depth;
        Uint16 ArrayLayers, Levels, Samples;
        Uint8 FixedSampleLocations, Immutable;
        Uint32 Usage;        // BufferUsage
        Uint32 StorageFlags; // glBufferStorage flags
        Uint8 HasDefinedContent;  // false after a NULL-data respecify
        Uint8 ImageBindableHint;  // client-side everImageBound; pre-emptive allocation
        Uint16 Pad0;
        // Diagnostics only. A GL name is NEVER an identity, never a memo key and never part
        // of a content hash (section 4.2.1). Widened from the plan's two bytes, which
        // cannot hold one.
        Uint32 GlNameForDiag;
        Uint32 Pad1;
        MGPipeHandle ViewOf;             // storage owner for a texture view
        MGPipeHandle BufferForTexBuffer; // texture-buffer backing store
        Uint64 BufOffset, BufSize;       // kWholeBuffer == ~0, resolved live
    };
    MGP_ASSERT_POD(MGPResourceDesc, 88);
    inline constexpr Uint64 kMGPipeWholeBuffer = ~0ull;

    struct MGPFenceWait {
        MGPipeHandle Fence;
        Uint64 TimeoutNs;
    };
    MGP_ASSERT_POD(MGPFenceWait, 16);

    struct MGPQueryDesc {
        MGPipeHandle Query;
        Uint32 Kind;   // GL query target
        Uint32 Stream; // indexed query stream, 0 otherwise
    };
    MGP_ASSERT_POD(MGPQueryDesc, 16);

    struct MGPQueryResultRequest {
        MGPipeHandle Query;
        Uint8 Wait; // the two-value contract of GetSyncStatus is preserved verbatim
        Uint8 Pad0[3];
        Uint32 Pad1;
    };
    MGP_ASSERT_POD(MGPQueryResultRequest, 16);

    // query_timestamp: glGetInteger64v(GL_TIMESTAMP), the synchronous "what time is it on the
    // GPU" GLFunctionsTable::GetGpuTimestampNs answers today. The request names nothing; the
    // Int64 nanosecond stamp comes back through the reply slot.
    struct MGPTimestampRequest {
        Uint32 Reserved;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPTimestampRequest, 8);

    // ---------------------------------------------------------------------------------
    // CSOs
    // ---------------------------------------------------------------------------------

    // create_render_state carries ONLY the pipeline subset's chunk bytes. chunkMask lets an
    // incremental create send just the chunks that moved, against baseCso (section 4.5.2).
    struct MGPRenderStateDesc {
        MGPipeHandle Cso;
        MGPipeHandle BaseCso;
        Uint32 ChunkMask; // all ones for a brand new CSO
        Uint32 Pad0;
        MGPBlobRef Blob;
    };
    MGP_ASSERT_POD(MGPRenderStateDesc, 48);

    // Steady state: 12 bytes on the wire, no hashing, no blob.
    struct MGPBindRenderState {
        MGPipeHandle Cso;
        Uint16 Version;
        Uint16 PipelineVersion;
    };
    MGP_ASSERT_POD(MGPBindRenderState, 12);

    // The half of the render state that must NOT mint a CSO: viewport, scissor, depth
    // range, blend colour, line width, polygon offset, stencil ref/write mask, clear
    // values, sample coverage, hints and the point-size family. This is what keeps
    // glViewport from evicting Magma's pipeline memo (D-B1).
    struct MGPDynamicState {
        Uint32 ChunkMask;
        Uint16 Version;
        Uint16 Pad0;
        MGPBlobRef Blob;
    };
    MGP_ASSERT_POD(MGPDynamicState, 32);

    // Both views travel, and neither is derivable from the other: the resolved
    // VertexAttribute[32] AND the binding points, because a pointer-call stride of 0 means
    // "element size" while a binding-model stride of 0 means "every vertex reads the same
    // element" (section 4.5.3). IsLong and Type == Float64 are carried separately.
    struct MGPVertexElements {
        MGPipeHandle Cso;
        Uint32 AttributeCount;
        Uint32 BindingPointCount;
        MGPBlobRef Blob; // VertexAttribute[] followed by VertexBufferBindingPoint[]
    };
    MGP_ASSERT_POD(MGPVertexElements, 40);

    // SamplerParameters crosses byte for byte INCLUDING borderColorForm: without it the
    // backend cannot choose between glSamplerParameterIiv and fv, or between the
    // VkBorderColor families, because all three representations are always numerically
    // populated (section 4.5.4). Carried as a blob until P0.5 gives it a value header.
    struct MGPSamplerDesc {
        MGPipeHandle Cso;
        MGPBlobRef Parameters;
    };
    MGP_ASSERT_POD(MGPSamplerDesc, 32);

    // = pipe_sampler_view, and ONLY the view restrictions. Everything a glTexParameter
    // writes lives on set_texture_params instead, because a texture that is only an FBO
    // attachment, only an image binding or only a glCopyImageSubData endpoint has no
    // sampler view to hang it on (section 4.4.3).
    struct MGPSamplerView {
        MGPipeHandle Cso;
        MGPipeHandle Texture;
        Uint32 InternalFormat; // aliasing format for glTextureView
        Uint8 Target;
        Uint8 Pad0[3];
        Uint16 MinLevel, NumLevels, MinLayer, NumLayers;
        Uint16 Samples;
        Uint8 FixedSampleLocations;
        Uint8 Pad1;
    };
    MGP_ASSERT_POD(MGPSamplerView, 36);

    // Per texture OBJECT, independent of any view.
    struct MGPTextureParams {
        MGPipeHandle Res;
        Uint16 BaseLevel, MaxLevel;
        Uint8 Swizzle[4];
        Uint8 DepthStencilMode;
        // Mirrors m_forceTextureParamsResync: the widened-channel carrier needs a swizzle
        // override that the frontend params version does not move for.
        Uint8 ForceResync;
        Uint8 Pad0[2];
        Float MinLod, MaxLod, LodBias;
    };
    MGP_ASSERT_POD(MGPTextureParams, 32);

    // create_shader_state. The reflection blob is the whole LinkArtifacts + SpirvArtifacts
    // archive; P0.5 extracts those types out of ProgramObject.h so a server can
    // deserialize into them without dragging in glslang (section 4.5.5).
    struct MGPProgramDesc {
        MGPipeHandle Cso;
        Uint32 StageMask; // == GetLinkedShaderStages()
        Uint32 GlobalUboSize;
        Uint32 ReservedNumSamplesOffset;
        Uint8 SpirvStatus;
        Uint8 NativeFloat64;
        Uint8 PointSizeDemoted;
        Uint8 EnableSpirvValidation;
        MGPBlobRef Spirv[6]; // per stage
        MGPBlobRef Reflection;
    };
    MGP_ASSERT_POD(MGPProgramDesc, 192);

    // ---------------------------------------------------------------------------------
    // set_*
    // ---------------------------------------------------------------------------------

    // = pipe_surface. internalFormat is INLINE so the four cross-object masks fall out at
    // push time with no lookup (section 4.5.6).
    struct MGPSurface {
        MGPipeHandle Res;
        Uint32 InternalFormat;
        Uint8 Kind; // Texture | Renderbuffer | None
        Uint8 Layered;
        Uint16 Level;
        Uint32 Layer;
        Uint16 UploadTarget;
        Uint16 Pad0;
    };
    MGP_ASSERT_POD(MGPSurface, 24);

    struct MGPFramebufferState {
        MGPipeHandle Fbo; // kMGPipeDefaultFramebuffer for the default framebuffer
        MGPSurface Color[8];
        MGPSurface Depth, Stencil;
        // The RESOLVED read surface, not an index. This is what structurally closes the
        // read-buffer-shared-FBO defect class.
        MGPSurface ReadSurface;
        Int8 DrawBuffers[8]; // attachment index, -1 = NONE
        Uint16 Width, Height, Layers, Samples;
        Uint8 FixedSampleLocations, IsDefault, Complete, Pad0;
        Uint32 Pad1;
        // Two jobs (section 4.5.6): the server's render-pass memo key, and the CLIENT's
        // emission suppressor - an unchanged hash means this record is not sent at all.
        // The same pattern is mandatory for every kVarTail set_* below, or 26.2's
        // redundant glBindSampler traffic reappears as a variable-length record per batch.
        Uint64 ContentHash;
    };
    MGP_ASSERT_POD(MGPFramebufferState, 304);

    struct MGPVertexBuffer {
        MGPipeHandle Res;
        Uint64 Offset;
        Uint32 Stride;
        Uint32 Divisor;
        Uint32 BindingIndex;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPVertexBuffer, 32);

    // Var-tail header: MGPVertexBuffer[Count] follows.
    struct MGPVertexBuffers {
        Uint32 Start, Count;
        Uint64 ContentHash;
    };
    MGP_ASSERT_POD(MGPVertexBuffers, 16);

    // An independent call, NOT a subset of the VAO configuration version (D5).
    struct MGPIndexBuffer {
        MGPipeHandle Res;
        Uint64 Offset;
        Uint32 IndexSize;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPIndexBuffer, 24);

    struct MGPIndirectBuffers {
        MGPipeHandle DrawIndirect;
        MGPipeHandle Parameter;
    };
    MGP_ASSERT_POD(MGPIndirectBuffers, 16);

    // One entry of set_sampler_views. No stage dimension: MobileGL's texture unit space is
    // MERGED (TextureState::m_textureUnits is one Array of MAX_TEXTURE_IMAGE_UNITS = 192),
    // and the same unit may be sampled from two stages (section 4.4.3).
    struct MGPBoundView {
        MGPipeHandle View;
        MGPipeHandle Texture;
        Uint32 Unit;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPBoundView, 24);

    struct MGPSamplerViews {
        Uint32 Start, Count;
        Uint64 ContentHash;
    };
    MGP_ASSERT_POD(MGPSamplerViews, 16);

    // Var-tail header: MGPipeHandle[Count] of sampler CSOs follows.
    struct MGPSamplerStates {
        Uint32 Start, Count;
        Uint64 ContentHash;
    };
    MGP_ASSERT_POD(MGPSamplerStates, 16);

    struct MGPImageView {
        MGPipeHandle Res;
        Uint32 Unit;
        Uint32 InternalFormat;
        Uint32 Layer;
        Uint16 Level;
        Uint8 Layered;
        Uint8 Access;
    };
    MGP_ASSERT_POD(MGPImageView, 24);

    struct MGPShaderImages {
        Uint32 Start, Count;
        Uint64 ContentHash;
    };
    MGP_ASSERT_POD(MGPShaderImages, 16);

    // One bound buffer range: 24 bytes, no inline host span. The named-UBO host bytes a
    // backend needs under kCapNeedsHostUboBytes (D-B8) travel as an OPTIONAL second var-tail,
    // MGHostSpan[HostSpanCount] behind the ranges, announced by MGPShaderBuffers below. An
    // inline span would have cost every SSBO, atomic-counter and XFB range 32 dead bytes, and
    // D-B8 says not to freeze that payload's shape before the stage-ubo-named counter has
    // produced numbers.
    struct MGPBufferRange {
        MGPipeHandle Res;
        Uint64 Offset;
        Uint64 Size;
    };
    MGP_ASSERT_POD(MGPBufferRange, 24);

    // Var-tail header: MGPBufferRange[Count], then MGHostSpan[HostSpanCount]. HostSpanCount is
    // 0, or Count for the Uniform class under kCapNeedsHostUboBytes (a range with nothing to
    // ship carries an empty span, so the two arrays stay index-aligned).
    struct MGPShaderBuffers {
        Uint32 Class; // Uniform | ShaderStorage | AtomicCounter
        Uint32 Start;
        Uint32 Count;
        Uint32 WritableMask;
        Uint32 HostSpanCount; // 0, or Count when the kHostSpan tail is present (D-B8)
        Uint32 Pad0;
        Uint64 ContentHash;
    };
    MGP_ASSERT_POD(MGPShaderBuffers, 32);

    // Var-tail header: MGPBufferRange[Count] then Uint32 offsets[Count].
    struct MGPStreamOutputTargets {
        Uint32 Count;
        Uint32 Pad0;
        Uint64 Generation;
        Uint64 ContentHash;
    };
    MGP_ASSERT_POD(MGPStreamOutputTargets, 24);

    // Covers the DEFAULT UNIFORM BLOCK only (D6).
    struct MGPGlobalConstants {
        MGPipeHandle ShaderCso;
        Uint32 Version;
        Uint32 Pad0;
        MGPBlobRef Blob;
    };
    MGP_ASSERT_POD(MGPGlobalConstants, 40);

    // The float/int/uint view is resolved on the CLIENT by ClassifyVertexAttribType.
    struct MGPAttribValue {
        Uint32 Location;
        Uint8 ValueClass; // Float | Int | Uint | Double
        Uint8 Pad0[3];
        Uint32 Data[4];
    };
    MGP_ASSERT_POD(MGPAttribValue, 24);

    // Var-tail header: MGPAttribValue[popcount(Mask)] follows.
    struct MGPVertexAttribDefaults {
        Uint32 Mask;
        Uint32 Count;
    };
    MGP_ASSERT_POD(MGPVertexAttribDefaults, 8);

    // PACK only. There is deliberately no unpack counterpart: nothing on the far side of
    // the boundary reads unpack state (section 4.6 D5), and the staged-repack upload path
    // does not even issue glPixelStorei.
    struct MGPPixelPackState {
        PixelStoreParameters Pack;
    };
    static_assert(std::is_trivially_copyable_v<MGPPixelPackState>);
    // 28 is what PixelStoreParameters measures: two Bools, two bytes of padding, six Ints.
    // Asserting against sizeof(PixelStoreParameters) itself was a tautology that could not
    // notice the value struct changing width under the wire format.
    static_assert(sizeof(MGPPixelPackState) == 28,
                  "MGPPixelPackState changed size; update the wire format and this assertion");

    // Also a shader-variant input: both backends bake these into the synthesized
    // pass-through control stage.
    struct MGPPatchState {
        Uint32 Vertices;
        Uint32 Pad0;
        Float Outer[4];
        Float Inner[2];
        Uint32 Pad1[2];
    };
    MGP_ASSERT_POD(MGPPatchState, 40);

    // Migration-only (section 6.3). Every stage removes fields and lowers
    // MGL_RESIDUAL_BLOCK_SIZE; P13 asserts it is zero, which is the retirement trip wire.
    //
    // Layout must be asserted MEMBER BY MEMBER, not only by sizeof: a heterogeneous POD
    // union is where padding differs across ABIs, and the monolith verify harness is blind
    // to it because both sides are the same translation unit. G3 emits the offsetof
    // assertions; under split the block is serialized field-wise rather than memcpy'd.
    struct ResidualValueBlock {
        RenderStateParameters RenderState; // until create/bind_render_state + set_dynamic_state land
        PixelStoreParameters Pack;         // until set_pixel_pack_state lands
        Uint64 CapabilityBits;
        Uint32 PatchVertices;
        Uint32 Pad0;
        Float PatchOuter[4];
        Float PatchInner[2];
        Uint32 Pad1[2];
    };
    static_assert(std::is_trivially_copyable_v<ResidualValueBlock>);
// The retirement ratchet. This number only ever goes DOWN: every stage that lands a real
// set_* call deletes fields here and lowers it, and P13 replaces it with
// static_assert(sizeof(ResidualValueBlock) == 0), which stays red until the last field is
// gone. Shrinking the block without lowering the number, or growing it at all, is a build
// break - which is the point.
//
// Stable across the ABIs MobileGL ships on: every member of RenderStateParameters and
// PixelStoreParameters is a fixed-width scalar or an array of one, with no pointer and no
// SizeT.
#define MGL_RESIDUAL_BLOCK_SIZE 1248
    static_assert(sizeof(ResidualValueBlock) == MGL_RESIDUAL_BLOCK_SIZE,
                  "the residual value block changed size; lower MGL_RESIDUAL_BLOCK_SIZE if a field "
                  "retired, and do not raise it");

    struct MGPResidualValueState {
        Uint32 Version;
        Uint32 Pad0;
        MGPBlobRef Blob;
    };
    MGP_ASSERT_POD(MGPResidualValueState, 32);

    // ---------------------------------------------------------------------------------
    // Transfer
    // ---------------------------------------------------------------------------------

    // Shape copied from the unpack ring's existing UnpackStagingBlock. The source strides
    // are CARRIED, not inferred from a pointer comparison: the old
    // `uploadData == mipData` test cannot survive a split, where the client neither ships
    // the whole level nor keeps a server-side mirror of it (section 4.5.6).
    struct MGPSubRegion {
        Int32 X, Y, Z;
        Uint32 W, H, D;
        Uint64 SrcOffset;      // into the blob
        Uint32 SrcRowStride;   // bytes; 0 = tightly packed (w * bpp)
        Uint32 SrcSliceStride; // bytes; 0 = tightly packed
    };
    MGP_ASSERT_POD(MGPSubRegion, 40);

    // Carries the union box AND the region list so the SERVER picks the upload shape - the
    // decision belongs on the side that pays the GPU cost. Mali prices texture upload by
    // JOB COUNT: ~100 sprite rects against one union box measured +6 ms/frame.
    //
    // THE BUFFER HALF. With Target == Buffer there is no level and no box, so the destination
    // byte range rides in the box's first coordinate and first extent: UnionBox.X is the byte
    // offset, UnionBox.W the byte size, Y = Z = 0, H = D = 1, Level = 0, RegionCount = 0, and
    // Blob holds exactly Size source bytes. That caps ONE record at a 2^31-1 offset and a
    // 2^32-1 size; a range beyond either is split by the emitter - the same rule, and at
    // SEG_STAGE's 32 MiB the far tighter one, that the ring's half-capacity bound already
    // imposes on it. MGPipeSetSubDataBufferRange / MGPipeSubDataBufferOffset / Size below are
    // the only spelling of this convention; nothing else reads the box for a buffer.
    struct MGPSubData {
        MGPipeHandle Res;
        Uint16 Target, Level;
        // Replaces the backend's `uploadData == mipData` pointer comparison: are these
        // bytes an untransformed level shadow?
        Uint8 SourceIsVerbatimLevelShadow;
        Uint8 Pad0[3];
        MGPBox UnionBox;
        Uint32 RegionCount; // MGPSubRegion[] in the variable tail
        Uint32 Pad1;
        MGPBlobRef Blob;
    };
    MGP_ASSERT_POD(MGPSubData, 72);

    // Encodes a buffer byte range into the record's box. False, with the record untouched,
    // when the range does not fit one record: the emitter has to split it.
    inline Bool MGPipeSetSubDataBufferRange(MGPSubData& record, Uint64 offset, Uint64 size) {
        if (offset > 0x7FFFFFFFull || size > 0xFFFFFFFFull) {
            return false;
        }
        record.UnionBox = MGPBox{static_cast<Int32>(offset), 0, 0, static_cast<Uint32>(size), 1, 1};
        record.Level = 0;
        record.RegionCount = 0;
        return true;
    }
    inline Uint64 MGPipeSubDataBufferOffset(const MGPSubData& record) {
        // A negative X is a corrupt record (the encoder never writes one); read as unsigned
        // it lands above the encodable bound, which the applier's bounds gate refuses.
        return static_cast<Uint64>(static_cast<Uint32>(record.UnionBox.X));
    }
    inline Uint64 MGPipeSubDataBufferSize(const MGPSubData& record) { return record.UnionBox.W; }

    // The forward terminator for a server-initiated texture pull (section 7.1). May carry
    // zero regions - that is how a pull that needs nothing is answered.
    struct MGPSubDataComplete {
        MGPipeHandle Res;
        Uint16 Target, FirstLevel, LevelCount, Pad0;
        Uint64 PullSerial;
    };
    MGP_ASSERT_POD(MGPSubDataComplete, 24);

    // Carries the application's REAL access flags, not a normalized subset.
    struct MGPFlushRange {
        MGPipeHandle Res;
        Uint64 Offset, Size;
        Uint32 AccessFlags; // Flags<BufferMappingAccessBit>
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPFlushRange, 32);

    struct MGPReadback {
        MGPipeHandle Res;
        Uint64 Offset, Size;
    };
    MGP_ASSERT_POD(MGPReadback, 24);

    struct MGPCopyRegion {
        MGPipeHandle Src, Dst;
        MGPBox SrcBox;
        Int32 DstX, DstY, DstZ;
        Uint16 SrcTarget, DstTarget;
        Uint16 SrcLevel, DstLevel;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPCopyRegion, 64);

    struct MGPBlit {
        MGPipeHandle ReadFbo, DrawFbo;
        Int32 SrcX0, SrcY0, SrcX1, SrcY1;
        Int32 DstX0, DstY0, DstX1, DstY1;
        Uint32 Mask;
        Uint32 Filter;
    };
    MGP_ASSERT_POD(MGPBlit, 56);

    // One discriminated record replacing glClear, the four glClearBuffer* and the four
    // glClearNamedFramebuffer* entry points (section 4.4.4).
    struct MGPClear {
        MGPipeHandle Fbo;
        Uint32 Kind;   // Whole | Color | Depth | Stencil | DepthStencil
        Int32 DrawBufferIndex;
        Uint32 BufferMask; // GL_COLOR_BUFFER_BIT etc. for the whole-framebuffer form
        Uint32 ValueClass; // Float | Int | Uint
        Uint32 ColorValue[4];
        Float DepthValue;
        Int32 StencilValue;
    };
    MGP_ASSERT_POD(MGPClear, 48);

    struct MGPMipPlan {
        MGPipeHandle Res;
        Uint16 Target, BaseLevel, LevelCount, Pad0;
    };
    MGP_ASSERT_POD(MGPMipPlan, 16);

    // read_pixels and get_texture_image share one shape; both answer into a reply slot.
    struct MGPReadbackInfo {
        MGPipeHandle Res; // null for read_pixels: the bound read surface answers
        MGPBox Box;
        Uint32 Format, Type;
        Uint16 Target, Level;
        Uint32 Pad0;
        Uint64 DstOffset, DstSize;
    };
    MGP_ASSERT_POD(MGPReadbackInfo, 64);

    // ---------------------------------------------------------------------------------
    // Commands
    // ---------------------------------------------------------------------------------

    enum MGPDrawFlagBit : Uint8 {
        kDrawHasUserIndices = 1u << 0,
        kDrawPrimitiveRestart = 1u << 1,
        kDrawIndicesAreClient = 1u << 2,
        kDrawHasIndexRange = 1u << 3,
        kDrawHasXfbCount = 1u << 4,
    };

    // = pipe_draw_info. Today's twenty draw entry points collapse onto this one call, with
    // MGPDrawRange[] holding exactly the shape the glMultiDraw* family already has.
    //
    // minIndex/maxIndex are computed only on the client-memory array path today, and
    // xfbCpuCapturedVertices only on the XFB scatter path, so Flags gates the WORK. They
    // stay in the fixed head; moving them into the variable tail is a wire-format decision
    // that belongs with the transport (P5), where per-draw byte histograms exist to size
    // it. userIndices is in the variable tail already, so the VBO path - every Minecraft
    // and Sodium draw - never pays the 32 bytes of an MGHostSpan.
    struct MGPDrawInfo {
        Uint32 Mode;
        Uint8 IndexSize; // 0 = arrays, else 1 / 2 / 4
        Uint8 Flags;     // MGPDrawFlagBit
        Uint16 Pad0;
        Uint32 InstanceCount, StartInstance;
        Uint32 RestartIndex;
        Uint32 DrawIdOffset;
        MGPipeHandle IndexResource;
        Uint32 MinIndex, MaxIndex; // ~0 = unknown
        Uint64 XfbCpuCapturedVertices;
        Uint32 NumDraws; // MGPDrawRange[] in the variable tail
        Uint32 Pad1;
    };
    MGP_ASSERT_POD(MGPDrawInfo, 56);

    // = pipe_draw_start_count_bias.
    struct MGPDrawRange {
        Uint32 Start, Count;
        Int32 IndexBias;
    };
    MGP_ASSERT_POD(MGPDrawRange, 12);

    // Present when the draw is indirect. The client resolves the COUNT itself, so the
    // server never reads an indirect command block to learn how many draws there are.
    struct MGPDrawIndirect {
        MGPipeHandle Buffer;
        MGPipeHandle ParameterBuffer;
        Uint64 Offset, ParameterOffset;
        Uint32 Stride, DrawCount;
    };
    MGP_ASSERT_POD(MGPDrawIndirect, 40);

    struct MGPGridInfo {
        Uint32 GridX, GridY, GridZ;
        Uint32 BlockX, BlockY, BlockZ;
        MGPipeHandle IndirectBuffer;
        Uint64 IndirectOffset;
        Uint8 IsIndirect;
        Uint8 Pad0[7];
    };
    MGP_ASSERT_POD(MGPGridInfo, 48);

    struct MGPMemoryBarrier {
        Uint32 Bits; // GLbitfield
        Uint8 ByRegion;
        Uint8 Pad0[3];
    };
    MGP_ASSERT_POD(MGPMemoryBarrier, 8);

    struct MGPStreamOutputBegin {
        Uint32 PrimitiveMode;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPStreamOutputBegin, 8);

    // end_stream_output carries the accounting the client owns; the scatter itself is a
    // read-modify-write of the client's shadow and lives there (section 7.2.1).
    struct MGPXfbAccounting {
        Uint64 CapturedVertices;
        Uint64 PrimitivesWritten;
        Uint32 PrimitiveMode;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPXfbAccounting, 24);

    struct MGPStreamOutputControl {
        Uint32 Reserved;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPStreamOutputControl, 8);

    struct MGPFlush {
        Uint32 Flags;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPFlush, 8);

    struct MGPPresent {
        Uint64 FrameSerial;
    };
    MGP_ASSERT_POD(MGPPresent, 8);

    struct MGPSwapInterval {
        Int32 Interval;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPSwapInterval, 8);

    // ---------------------------------------------------------------------------------
    // Reverse channel payloads (section 7.1)
    // ---------------------------------------------------------------------------------

    struct MGPSurfaceInfo {
        Uint32 Width, Height;
        Uint32 InternalFormat;
        Uint16 Samples, Layers;
        Uint8 IsDefault;
        Uint8 Pad0[7];
    };
    MGP_ASSERT_POD(MGPSurfaceInfo, 24);

#undef MGP_ASSERT_POD
} // namespace MobileGL::MG_Pipe
