// MobileGL - MobileGL/MG_Pipe/MGPipeTypes.h
// Copyright (c) 2025-2026 MobileGL-Dev
// Licensed under the GNU Lesser General Public License v3.0:
//   https://www.gnu.org/licenses/gpl-3.0.txt
//   https://www.gnu.org/licenses/lgpl-3.0.txt
// SPDX-License-Identifier: LGPL-3.0-only
// End of Source File Header

#pragma once
#include <Includes.h>

#include "MGPipeHandles.h"
#include "MGPipeHostSpan.h"

// Every MGPipe payload (plan B section 4.5). Each one is a flat POD with explicit padding,
// carries a static_assert on trivial copyability and one on its exact size, and never
// contains a pointer: MGHostSpan, the one shape that changes with the transport, only ever
// rides in a variable tail (draw_vbo's user indices, set_shader_buffers' named-UBO bytes),
// never inline in a fixed payload.
//
// Sizes are asserted rather than merely documented because the wire records generated from
// these structs (generated/PipeWire.inc) are memcpy'd; a field silently changing width is a
// protocol break that no test would otherwise see.
//
// P0.5 DEBT, half repaid. The MG_State half is gone: ResidualValueBlock's
// RenderStateParameters and PixelStoreParameters now come from MGPipeValueTypes.h, so
// this header no longer reaches RenderState.h (its closure still touches TextureEnum.h,
// through BackendObject.h, for the reason in the next sentence). What remains is MGPCaps embedding
// MG_Backend's DynamicBackendParameters - deliberate, the caps block IS that struct
// (section 4.4.1) - and that one include is what still keeps purity gate A (section
// 10.3) off this header; the gate asserts MGPipeValueTypes.h instead. The caps block
// needs fixed-width members before it can move (a type change, not a move): P1/P7.
#include <MG_Backend/BackendObject.h>
#include "MGPipeValueTypes.h"

namespace MobileGL::MG_Pipe {
    using MG_Backend::DynamicBackendParameters;
    // Both live directly in namespace MobileGL and, since P0.5, are declared in
    // MG_Pipe/MGPipeValueTypes.h.
    using MobileGL::PixelStoreParameters;
    using MobileGL::RenderStateParameters;

    // A payload must be memcpy-able and its size must be an exact, stated number.
#define MGP_ASSERT_POD(T, Size)                                                                                        \
    static_assert(std::is_trivially_copyable_v<T>, #T " must be trivially copyable");                                  \
    static_assert(sizeof(T) == (Size), #T " changed size; update the wire format and this assertion")

    // ---------------------------------------------------------------------------------
    // Shared primitives
    // ---------------------------------------------------------------------------------

    // A run of bytes in the command stream's blob area. Monolith: Seg is
    // kMGHostSpanSegNone and Offset is an address into the caller's staging arena. Split:
    // Seg names a transport segment.
    struct MGPBlobRef {
        Uint64 Offset;
        Uint64 Size;
        Uint32 Seg;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPBlobRef, 24);

    struct MGPRange {
        Uint64 Offset;
        Uint64 Size;
    };
    MGP_ASSERT_POD(MGPRange, 16);

    // Destination box in the level's own coordinate system (section 4.5.6).
    struct MGPBox {
        Int32 X, Y, Z;
        Uint32 W, H, D;
    };
    MGP_ASSERT_POD(MGPBox, 24);

    // Where an asynchronous answer lands. Every server query in this catalogue is
    // async-with-handle; none of them blocks (section 4.4.6, "the total rule").
    struct MGPReplySlot {
        Uint64 Id;
    };
    MGP_ASSERT_POD(MGPReplySlot, 8);

    // One contiguous run of RenderStateParameters bytes. The pipeline/dynamic split is
    // defined exactly once, in MGPipeRenderStateSpans, and generated by G7 from the field
    // list VulkanRenderer::ComputePipelineStateHash already hashes (section 4.5.2).
    struct MGPStateChunk {
        Uint16 Offset;
        Uint16 Length;
    };
    MGP_ASSERT_POD(MGPStateChunk, 4);

    // The payload of every call that carries nothing but an object identity.
    struct MGPHandleOnly {
        MGPipeHandle Handle;
        Uint32 Kind; // MGPipeKind, widened for a stable wire size
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPHandleOnly, 16);

    // ---------------------------------------------------------------------------------
    // Screen: caps, resources, fences
    // ---------------------------------------------------------------------------------

    // Capability bits that replace "is this table slot null" as an implicit feature probe
    // (section 4.4.1). The five ownership-switch bits of v1 are deliberately absent: what
    // they tried to express - who performs primitive-restart rewriting and multi-draw
    // flattening - is not expressible as a capability (D-B7).
    enum MGPCapBit : Uint64 {
        kCapNone = 0,
        kCapViewportArray = 1ull << 0,
        kCapFloat64VertexAttrib = 1ull << 1,
        kCapResidentSubData = 1ull << 2,
        kCapCpuXfbPrimitiveAccounting = 1ull << 3,
        kCapTimerQuery = 1ull << 4,
        kCapOcclusionQuery = 1ull << 5,
        kCapXfbPrimitivesQuery = 1ull << 6,
        // The server rewrites restart indices / flattens multi-draws itself and therefore
        // needs the index bytes on its side: under split this arms the index host mirror
        // (D-B7).
        kCapNeedsHostIndexBytes = 1ull << 7,
        // The server packs named uniform blocks into its own ring and therefore needs the
        // host bytes of a set_shader_buffers(Uniform) range (D-B8).
        kCapNeedsHostUboBytes = 1ull << 8,
    };

    struct MGPCaps {
        // The ~90 flat scalars the backends already publish, by inclusion rather than by
        // restatement: a caps field added there must not need a second edit here. This is
        // also where the six per-axis compute limits (MaxComputeWorkGroupCount/Size) ride -
        // the only indexed answers the device owns, and therefore the only ones that outlive
        // the GetIntegeri_v table entry (see the PipeCalls.def footer).
        DynamicBackendParameters Dynamic;
        Uint64 CallMask; // MGPCapBit
        // The two halves that are not flat PODs travel as blobs: the format capability
        // cache holds Vector<Int> sample-count lists, and the renderer strings are
        // Strings. Their serializers land with the transport (P5).
        MGPBlobRef FormatCapabilities;
        MGPBlobRef RendererInfo;
    };
    static_assert(std::is_trivially_copyable_v<MGPCaps>, "MGPCaps must be trivially copyable");
    // Stated as a COMPOSITION rather than a literal: DynamicBackendParameters still carries
    // SizeT fields, so its literal size is ABI-dependent until P0.5 moves the caps block
    // into MGPipeValueTypes.h with fixed-width members. The assertion still fires on any
    // padding introduced between the members below.
    static_assert(sizeof(MGPCaps) == sizeof(DynamicBackendParameters) + 8 + 24 + 24,
                  "MGPCaps gained padding or a member; update the wire format");

    // ---------------------------------------------------------------------------------
    // MGPResourceDesc's two discriminators (P4a, D-A3 / D-A4)
    // ---------------------------------------------------------------------------------

    // MGPResourceDesc::Target. P3a minted no enum for this list because it had exactly one
    // producer and used the leading member's value (0) for it; P4a's texture family is the
    // second producer, so the list is written out here, beside the field, in the order the
    // field's own comment already wrote it.
    //
    // TexRect IS A THIRTEENTH ENUMERATOR AND THE BRIEF'S LIST HAS TWELVE. MobileGL's
    // TextureTarget has TextureRectangle (MG_State/GLState/TextureState/TextureEnum.h), the
    // table below may not have a `default:` arm, and folding rectangle onto Tex2D would erase
    // a distinction the frontend keeps and both backends switch on (Espryt's
    // MapToBackendTextureTarget lowers Tex1D the same way and Tex1D still has its own
    // enumerator here). It is appended AFTER TexBuffer so every value the design document
    // names keeps the number it was given.
    enum class MGPipeResourceTarget : Uint8 {
        Buffer = 0,
        Tex1D,
        Tex2D,
        Tex3D,
        Tex1DArray,
        Tex2DArray,
        TexCube,
        TexCubeArray,
        Tex2DMS,
        Tex2DMSArray,
        Renderbuffer,
        TexBuffer,
        TexRect,
        Count,
    };

    // P3a's constant, moved here from MG_Impl/Pipe/ResourceTracker.h with the enum: the ack
    // predicate at the bottom of this header now names the buffer target explicitly (D-A2) and
    // may not reach into MG_Impl to do it. The static_assert is what keeps the two spellings
    // from drifting; nothing may open-code either.
    inline constexpr Uint8 kMGPipeResourceTargetBuffer =
        static_cast<Uint8>(MGPipeResourceTarget::Buffer);
    static_assert(kMGPipeResourceTargetBuffer == static_cast<Uint8>(MGPipeResourceTarget::Buffer),
                  "P3a's kMGPipeResourceTargetBuffer and MGPipeResourceTarget::Buffer have drifted");

    // A sentinel the table below returns for a TextureTarget enumerator it does not name. It
    // is NOT a legal Target value - it does not fit the field's Uint8 - so an unmapped
    // enumerator is a build break at the static_assert rather than a descriptor that quietly
    // describes the wrong kind of storage. Exactly kMGPipeBindUnmapped's shape.
    inline constexpr Uint32 kMGPipeResourceTargetUnmapped = 0x100u;

    // The one table. No `default:` arm on purpose - that is what makes the static_assert
    // below able to see an unnamed enumerator, and it is the shape
    // MGPipeBindMaskForBufferTarget already uses for BufferTarget.
    constexpr Uint32 MGPipeResourceTargetForTextureTarget(MobileGL::TextureTarget target) {
        switch (target) {
        case MobileGL::TextureTarget::Texture1D:
            return static_cast<Uint32>(MGPipeResourceTarget::Tex1D);
        case MobileGL::TextureTarget::Texture2D:
            return static_cast<Uint32>(MGPipeResourceTarget::Tex2D);
        case MobileGL::TextureTarget::Texture3D:
            return static_cast<Uint32>(MGPipeResourceTarget::Tex3D);
        case MobileGL::TextureTarget::TextureCubeMap:
            return static_cast<Uint32>(MGPipeResourceTarget::TexCube);
        // Its own enumerator rather than Tex2D: see the enum's comment.
        case MobileGL::TextureTarget::TextureRectangle:
            return static_cast<Uint32>(MGPipeResourceTarget::TexRect);
        case MobileGL::TextureTarget::Texture2DMultisample:
            return static_cast<Uint32>(MGPipeResourceTarget::Tex2DMS);
        case MobileGL::TextureTarget::TextureBuffer:
            return static_cast<Uint32>(MGPipeResourceTarget::TexBuffer);
        case MobileGL::TextureTarget::Texture1DArray:
            return static_cast<Uint32>(MGPipeResourceTarget::Tex1DArray);
        case MobileGL::TextureTarget::Texture2DArray:
            return static_cast<Uint32>(MGPipeResourceTarget::Tex2DArray);
        case MobileGL::TextureTarget::TextureCubeMapArray:
            return static_cast<Uint32>(MGPipeResourceTarget::TexCubeArray);
        case MobileGL::TextureTarget::Texture2DMultisampleArray:
            return static_cast<Uint32>(MGPipeResourceTarget::Tex2DMSArray);
        // NOT TEXTURE TARGETS. Listed rather than defaulted so the completeness assert still
        // sees them, and mapped to the sentinel because no descriptor may carry either: the
        // count is the enum's bound and Unknown is what an unresolved GL enum becomes.
        case MobileGL::TextureTarget::TextureTargetCount:
        case MobileGL::TextureTarget::Unknown:
            return kMGPipeResourceTargetUnmapped;
        }
        return kMGPipeResourceTargetUnmapped;
    }

    constexpr Bool MGPipeEveryTextureTargetIsMapped() {
        for (SizeT i = 0; i < static_cast<SizeT>(MobileGL::TextureTarget::TextureTargetCount); ++i) {
            if (MGPipeResourceTargetForTextureTarget(static_cast<MobileGL::TextureTarget>(i)) ==
                kMGPipeResourceTargetUnmapped) {
                return false;
            }
        }
        return true;
    }
    static_assert(MGPipeEveryTextureTargetIsMapped(),
                  "a TextureTarget enumerator has no MGPResourceDesc::Target row: add it to "
                  "MGPipeResourceTargetForTextureTarget, and give it an enumerator of its own "
                  "rather than folding it onto a neighbour (D-A3)");
    static_assert(MGPipeResourceTargetForTextureTarget(MobileGL::TextureTarget::Texture2D) !=
                      MGPipeResourceTargetForTextureTarget(MobileGL::TextureTarget::TextureRectangle),
                  "a rectangle texture is not a 2D texture on the wire; both backends switch on "
                  "the difference");

    // MGPResourceDesc::BindMask's twelve bits, in the order the field's comment names them.
    //
    // THEY LIVED IN MG_Impl/Pipe/ResourceTracker.h THROUGH P3a, with that file's own note
    // saying "the integrator moves them beside the field when a second producer appears
    // (P4a's texture family)". P4a is that producer: a texture sets kMGPipeBindSampler,
    // kMGPipeBindShaderImage, kMGPipeBindRenderTarget and kMGPipeBindDepthStencil, which are
    // the four bits nothing set before. The mask is STICKY - ORed, never cleared - and is
    // emitted on both resource_create and every resource_respecify.
    enum MGPipeBindBit : Uint16 {
        kMGPipeBindNone = 0,
        kMGPipeBindVertex = 1u << 0,
        kMGPipeBindIndex = 1u << 1,
        kMGPipeBindConstant = 1u << 2,
        kMGPipeBindShaderBuffer = 1u << 3,
        kMGPipeBindIndirect = 1u << 4,
        kMGPipeBindSampler = 1u << 5,
        kMGPipeBindShaderImage = 1u << 6,
        kMGPipeBindRenderTarget = 1u << 7,
        kMGPipeBindDepthStencil = 1u << 8,
        kMGPipeBindStreamOutput = 1u << 9,
        kMGPipeBindAtomic = 1u << 10,
        // THE D-B7 SWITCH. With kCapNeedsHostIndexBytes set the server mirrors this
        // resource's bytes so it can rewrite restart indices and flatten multi-draws
        // (ARCHITECTURE.md 10.3). Getting it wrong is invisible in monolith and silently
        // disables both under split, which is why it is set from a table rather than from a
        // special case at the emission site.
        kMGPipeBindElementArray = 1u << 11,
    };

    // Discriminated resource descriptor: buffers, every texture target and renderbuffers
    // share one create/respecify shape (section 4.5.1).
    struct MGPResourceDesc {
        MGPipeHandle Resource;
        // MGPipeResourceTarget: Buffer | Tex1D..TexCubeArray | Tex2DMS.. | Renderbuffer |
        // TexBuffer | TexRect. Never open-coded; the texture half comes from
        // MGPipeResourceTargetForTextureTarget above.
        Uint8 Target;
        Uint8 StorageKind; // == TextureStorageType (Mipmap | Buffer)
        // MGPipeBindBit, above: VERTEX|INDEX|CONSTANT|SHADER_BUFFER|INDIRECT|SAMPLER|
        // SHADER_IMAGE|RENDER_TARGET|DEPTH_STENCIL|STREAM_OUTPUT|ATOMIC|ELEMENT_ARRAY. The
        // ELEMENT_ARRAY bit is the D-B7 switch: with kCapNeedsHostIndexBytes set the server
        // mirrors this resource.
        Uint16 BindMask;
        Uint32 InternalFormat; // already resolved to an uncompressed fallback by the client
        Uint32 Width, Height, Depth;
        Uint16 ArrayLayers, Levels, Samples;
        Uint8 FixedSampleLocations, Immutable;
        Uint32 Usage;        // BufferUsage
        Uint32 StorageFlags; // glBufferStorage flags
        Uint8 HasDefinedContent;  // false after a NULL-data respecify - STORAGE-DEFINING
        Uint8 ImageBindableHint;  // client-side everImageBound; pre-emptive allocation
        Uint16 Pad0;
        // ImageBindableHint and BindMask above are the two METADATA fields the rule exists
        // for: a respecify that moves only them - every storage-defining field equal to the
        // stored descriptor - is a metadata update, with no reallocation ack and no
        // PendingUploads clear. The rule, the full storage-defining field set and the third
        // field allowed to differ (GlNameForDiag) are stated beside
        // MGPipeResourceRespecifyNeedsAck below (P4a, ID-18 M4), which is where the applier
        // and both twins read them from.
        // Diagnostics only. A GL name is NEVER an identity, never a memo key and never part
        // of a content hash (section 4.2.1). Widened from the plan's two bytes, which
        // cannot hold one.
        Uint32 GlNameForDiag;
        Uint32 Pad1;
        MGPipeHandle ViewOf;             // storage owner for a texture view
        MGPipeHandle BufferForTexBuffer; // texture-buffer backing store
        Uint64 BufOffset, BufSize;       // kWholeBuffer == ~0, resolved live
    };
    MGP_ASSERT_POD(MGPResourceDesc, 88);
    inline constexpr Uint64 kMGPipeWholeBuffer = ~0ull;

    struct MGPFenceWait {
        MGPipeHandle Fence;
        Uint64 TimeoutNs;
    };
    MGP_ASSERT_POD(MGPFenceWait, 16);

    struct MGPQueryDesc {
        MGPipeHandle Query;
        Uint32 Kind;   // GL query target
        Uint32 Stream; // indexed query stream, 0 otherwise
    };
    MGP_ASSERT_POD(MGPQueryDesc, 16);

    struct MGPQueryResultRequest {
        MGPipeHandle Query;
        Uint8 Wait; // the two-value contract of GetSyncStatus is preserved verbatim
        Uint8 Pad0[3];
        Uint32 Pad1;
    };
    MGP_ASSERT_POD(MGPQueryResultRequest, 16);

    // query_timestamp: glGetInteger64v(GL_TIMESTAMP), the synchronous "what time is it on the
    // GPU" GLFunctionsTable::GetGpuTimestampNs answers today. The request names nothing; the
    // Int64 nanosecond stamp comes back through the reply slot.
    struct MGPTimestampRequest {
        Uint32 Reserved;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPTimestampRequest, 8);

    // ---------------------------------------------------------------------------------
    // CSOs
    // ---------------------------------------------------------------------------------

    // create_render_state carries ONLY the pipeline subset's chunk bytes. chunkMask lets an
    // incremental create send just the chunks that moved, against baseCso (section 4.5.2).
    struct MGPRenderStateDesc {
        MGPipeHandle Cso;
        MGPipeHandle BaseCso;
        Uint32 ChunkMask; // all ones for a brand new CSO
        Uint32 Pad0;
        MGPBlobRef Blob;
    };
    MGP_ASSERT_POD(MGPRenderStateDesc, 48);

    // Steady state: 12 bytes on the wire, no hashing, no blob.
    struct MGPBindRenderState {
        MGPipeHandle Cso;
        Uint16 Version;
        Uint16 PipelineVersion;
    };
    MGP_ASSERT_POD(MGPBindRenderState, 12);

    // The half of the render state that must NOT mint a CSO: viewport, scissor, depth
    // range, blend colour, line width, polygon offset, stencil ref/write mask, clear
    // values, hints, the point-size family and the primitive-restart index. This is what
    // keeps glViewport from evicting Magma's pipeline memo (D-B1).
    //
    // SAMPLE COVERAGE IS NOT IN IT, and this comment used to say it was. P2's rule is that
    // a byte is pipeline state if and only if a public RenderState setter that calls
    // BumpVersions() writes it, and SetSampleCoverage does - so SampleCoverageValue and
    // SampleCoverageInvert are in pipeline chunk P2 (MGPipeRenderStateSpans.h).
    struct MGPDynamicState {
        Uint32 ChunkMask;
        Uint16 Version;
        Uint16 Pad0;
        MGPBlobRef Blob;
    };
    MGP_ASSERT_POD(MGPDynamicState, 32);

    // Both views travel, and neither is derivable from the other: the resolved
    // VertexAttribute[32] AND the binding points, because a pointer-call stride of 0 means
    // "element size" while a binding-model stride of 0 means "every vertex reads the same
    // element" (section 4.5.3). IsLong and Type == Float64 are carried separately.
    //
    // THE BLOB RULE - ONE RULE FOR EVERY RECORD IN THIS HEADER THAT CARRIES AN MGPBlobRef,
    // and MGPSubData below is the other one. `Blob.Size` is the record's own statement of how
    // many bytes its blob holds, and the applier holds the record to that statement WHENEVER
    // THE RECORD MAKES IT: a non-zero Blob.Size that disagrees with the byte length the
    // record's other fields describe is Fatal{ProtocolCorruption} and the call is refused. A
    // ZERO Blob.Size means "this record does not declare its blob", which is what a monolith
    // emission is - the bytes travel beside the record through the apply entry point's
    // companion `const void*` and no MGPBlobRef is filled - and it is not a fault. Either way
    // the bytes read are bounded by the record's OTHER fields (the two counts here, the
    // destination range there), so the length is a cross-check and never the safety property.
    // A transport that fills these in gets a real gate on the first record it truncates; a
    // client that leaves them zero gets no verify-build abort for a field it never used.
    struct MGPVertexElements {
        MGPipeHandle Cso;
        Uint32 AttributeCount;
        Uint32 BindingPointCount;
        // MGPVertexAttribWire[AttributeCount] followed by
        // MGPVertexBindingPointWire[BindingPointCount] - the WIRE views of MGPipeValueTypes.h,
        // not VertexAttribute / VertexBufferBindingPoint, which cannot travel at all (each
        // holds a SharedPtr<BufferObject>). The layout is stated once at
        // MGPipeValueTypes.h's P3a block and unpacked once in PipeApply.cpp.
        MGPBlobRef Blob;
    };
    MGP_ASSERT_POD(MGPVertexElements, 40);

    // SamplerParameters crosses byte for byte INCLUDING borderColorForm: without it the
    // backend cannot choose between glSamplerParameterIiv and fv, or between the
    // VkBorderColor families, because all three representations are always numerically
    // populated (section 4.5.4). Carried as a blob until P0.5 gives it a value header.
    struct MGPSamplerDesc {
        MGPipeHandle Cso;
        MGPBlobRef Parameters;
    };
    MGP_ASSERT_POD(MGPSamplerDesc, 32);

    // = pipe_sampler_view, and ONLY the view restrictions. Everything a glTexParameter
    // writes lives on set_texture_params instead, because a texture that is only an FBO
    // attachment, only an image binding or only a glCopyImageSubData endpoint has no
    // sampler view to hang it on (section 4.4.3).
    struct MGPSamplerView {
        MGPipeHandle Cso;
        MGPipeHandle Texture;
        Uint32 InternalFormat; // aliasing format for glTextureView
        Uint8 Target;
        Uint8 Pad0[3];
        Uint16 MinLevel, NumLevels, MinLayer, NumLayers;
        Uint16 Samples;
        Uint8 FixedSampleLocations;
        Uint8 Pad1;
    };
    MGP_ASSERT_POD(MGPSamplerView, 36);

    // Per texture OBJECT, independent of any view.
    //
    // P4a, D-E1: 32 -> 40 bytes. BuiltinSampler is the SamplerCso carrying the
    // SamplerParameters of the SamplerObject every ITextureObject owns
    // (TextureState/TextureObject.h's m_sampler, constructed by TextureObjectBase's
    // constructor). GL 4.6 core table 23.18 makes filter/wrap/compare/border SAMPLER state,
    // and Espryt pushes it with glTexParameter* onto the TEXTURE rather than with
    // glBindSampler onto the unit - behaviour P4a preserves exactly. Naming the CSO rather
    // than widening this payload with a filter/wrap/border block is what keeps ONE authority
    // for one value: SyncTextureParamsToBackend reads this record, SyncBuiltinSamplerToBackend
    // reads that CSO's SamplerParameters, and the two pushes stay two pushes.
    struct MGPTextureParams {
        MGPipeHandle Res;            //  0
        // Kind SamplerCso. kMGPipeNullHandle is ILLEGAL - every texture object owns a sampler
        // object, so a null here is Fatal{ProtocolCorruption} rather than "no sampler".
        MGPipeHandle BuiltinSampler; //  8
        Uint16 BaseLevel, MaxLevel;  // 16
        Uint8 Swizzle[4];            // 20
        Uint8 DepthStencilMode;      // 24
        // Mirrors m_forceTextureParamsResync: the widened-channel carrier needs a swizzle
        // override that the frontend params version does not move for.
        Uint8 ForceResync;           // 25
        // Mirrors m_forceSamplerResync, which had no wire spelling at all before P4a. What it
        // guards is not mis-filtering but an INCOMPLETE texture sampling (0,0,0,1) after a
        // driver re-mint, which is why it is a second bit and not folded into ForceResync.
        Uint8 SamplerResync;         // 26
        Uint8 Pad0;                  // 27
        Float MinLod, MaxLod, LodBias; // 28
    };
    MGP_ASSERT_POD(MGPTextureParams, 40);

    // MGPTextureParams::DepthStencilMode's two legal values, and the ONLY spelling of them
    // (P4a, ID-12 / esprytobj DV-2). The frontend keeps a GLenum - GL_DEPTH_COMPONENT 0x1902,
    // GL_STENCIL_INDEX 0x1901 - and a Uint8 cannot hold one, so the aspect is NUMBERED here
    // rather than truncated there. The GLenum -> byte helper belongs to the client emitter;
    // this header owns the two numbers, so the emitter and both backends cannot disagree.
    //
    // 0 IS DEPTH, AND THAT IS THE WHOLE REASON FOR THIS ORDER RATHER THAN THE ENUM'S LOW BYTE.
    // GL_DEPTH_COMPONENT is the GL initial value of GL_DEPTH_STENCIL_TEXTURE_MODE and a
    // texture that never asks for the stencil aspect never emits the call at all, so A ZEROED
    // RECORD MUST DECODE TO EXACTLY WHAT AN UNTOUCHED TEXTURE ALREADY HAS. Numbering by the
    // low byte would have made depth 0x02 and stencil 0x01 and left zero meaning nothing.
    inline constexpr Uint8 kMGPipeDepthStencilModeDepth = 0;   // GL_DEPTH_COMPONENT
    inline constexpr Uint8 kMGPipeDepthStencilModeStencil = 1; // GL_STENCIL_INDEX

    // create_shader_state. The reflection blob is the whole LinkArtifacts + SpirvArtifacts
    // archive; P0.5 extracts those types out of ProgramObject.h so a server can
    // deserialize into them without dragging in glslang (section 4.5.5).
    struct MGPProgramDesc {
        MGPipeHandle Cso;
        Uint32 StageMask; // == GetLinkedShaderStages()
        Uint32 GlobalUboSize;
        Uint32 ReservedNumSamplesOffset;
        Uint8 SpirvStatus;
        Uint8 NativeFloat64;
        Uint8 PointSizeDemoted;
        Uint8 EnableSpirvValidation;
        MGPBlobRef Spirv[6]; // per stage
        MGPBlobRef Reflection;
    };
    MGP_ASSERT_POD(MGPProgramDesc, 192);

    // ---------------------------------------------------------------------------------
    // set_*
    // ---------------------------------------------------------------------------------

    // MGPSurface::Kind's three values (P4a, ID-12 / esprytobj DV-4). MGPipeKind is REUSED
    // rather than a second three-value enum minted beside it: it already spells Texture and
    // Renderbuffer, its None is 0, and a zero-initialised MGPSurface is therefore ALREADY the
    // empty attachment point this record describes - {Res = kMGPipeNullHandle, Kind = None}
    // and every other field zero. The static_assert is what keeps that true if MGPipeKind is
    // ever reordered.
    inline constexpr Uint8 kMGPipeSurfaceKindNone = static_cast<Uint8>(MGPipeKind::None);
    inline constexpr Uint8 kMGPipeSurfaceKindTexture = static_cast<Uint8>(MGPipeKind::Texture);
    inline constexpr Uint8 kMGPipeSurfaceKindRenderbuffer =
        static_cast<Uint8>(MGPipeKind::Renderbuffer);
    static_assert(kMGPipeSurfaceKindNone == 0,
                  "a zero-initialised MGPSurface must already be the empty attachment point");

    // MGPSurface::TextureTarget for a point that names no texture: the renderbuffer point and
    // the empty point both carry it. It is MobileGL::TextureTarget::Unknown, which is -1 and
    // therefore 0xFFFF in the field's Uint16 - a value no real target has, so a reader that
    // forgets to gate on Kind gets a nonsense target rather than a plausible wrong one.
    inline constexpr Uint16 kMGPipeSurfaceNoTextureTarget = 0xFFFF;
    static_assert(kMGPipeSurfaceNoTextureTarget ==
                      static_cast<Uint16>(MobileGL::TextureTarget::Unknown),
                  "kMGPipeSurfaceNoTextureTarget is TextureTarget::Unknown widened to the "
                  "field, and MG_State moved Unknown off -1");

    // = pipe_surface. internalFormat is INLINE so the four cross-object masks fall out at
    // push time with no lookup (section 4.5.6).
    struct MGPSurface {
        MGPipeHandle Res;
        Uint32 InternalFormat;
        Uint8 Kind; // kMGPipeSurfaceKind{None,Texture,Renderbuffer}, above
        Uint8 Layered;
        Uint16 Level;
        Uint32 Layer;
        Uint16 UploadTarget; // static_cast<Uint16>(MobileGL::TextureUploadTarget)
        // P4a, ID-12 / esprytobj DV-5: WAS Pad0, and the size did not move - the two bytes
        // were already here. static_cast<Uint16>(MobileGL::TextureTarget), and
        // kMGPipeSurfaceNoTextureTarget on every point that is not a texture.
        //
        // THE FOUR CROSS-OBJECT MASKS ARE WHY IT EXISTS. IsSnormFallbackAttachment,
        // IsUnormFallbackAttachment and IsAlphaWidenedColorAttachment all reduce to
        // (format, TEXTURE TARGET) - ShouldUseCaveatTextureFormat(format, target) and
        // BackendTextureFormatAddsAlpha(format, target) - and no TextureUploadTarget ->
        // TextureTarget inverse exists anywhere in the tree, so UploadTarget cannot answer
        // them. Without this field D-C1's promise that the inline InternalFormat makes the
        // masks "fall out at push time with no lookup" is unkeepable and the backend keeps
        // reading the frontend attachment objects.
        //
        // CONSULTED ONLY WHEN Kind == kMGPipeSurfaceKindTexture. A zero-initialised record
        // carries 0, which is TextureTarget::Texture1D and not the sentinel; that is not a
        // defect, because such a record is Kind == None and names no texture at all. Gating
        // on Kind is the reader's contract.
        Uint16 TextureTarget;
    };
    MGP_ASSERT_POD(MGPSurface, 24);

    // P4a, D-C2/D-C3 and ID-19: THE RECORD DESCRIBES A FRAMEBUFFER OBJECT, and Target says
    // whether it ALSO moves a binding.
    //
    // A `Named` record describes the framebuffer object it names (Fbo) and changes NO
    // binding. `Draw` / `Read` / `Both` records describe the same object AND set the bound
    // handle(s) of the target(s) they name.
    //
    // The applier therefore keeps records PER FRAMEBUFFER OBJECT, keyed by the handle's slot
    // (the generation is checked on lookup and a stale one refuses; a framebuffer has no wire
    // lifetime - D-I2, the catalogue has no framebuffer delete - so a successor's record
    // simply OVERWRITES the slot), plus the two bound handles. And every DSA entry point that
    // hands a framebuffer to the server BY NAME - BlitNamedFramebuffer, the four
    // ClearNamedFramebuffer*, and the DSA attachment / draw-buffer / read-buffer setters at
    // their validate point - is PRECEDED BY A Named RECORD, so that any framebuffer the
    // server is about to receive by name already has one.
    //
    // That last rule is the phase's main correction, not a nicety. With only the two
    // bound-target records, glClearNamedFramebufferfv(fbo) on an unbound fbo made the backend
    // mint a fresh driver framebuffer with NO ATTACHMENTS, find no record for it, decline,
    // and then issue the clear against it anyway - GL_INVALID_FRAMEBUFFER_OPERATION and
    // nothing cleared, where the legacy arm cleared correctly. Writing such an object into
    // the bound-target record instead would have been worse: the applier would then claim it
    // is bound.
    //
    // GL has two independent framebuffer bindings and one record carries one Fbo, so a
    // Draw/Read pair is two records and one object bound to both targets is one record with
    // Both. The draw-buffer array belongs to the OBJECT the record names; it reaches the
    // driver's bound draw framebuffer only for a record whose Target is Draw or Both -
    // Espryt's own comment records the Minecraft 26.x OIT bug where a READ-only sync landed
    // glDrawBuffers on the wrong framebuffer - and a Named record's draw buffers are applied
    // when that object is next configured, never to whatever happens to be bound. ReadSurface
    // is resolved from THAT framebuffer's own read buffer in EVERY record, Named included,
    // which is what makes the read-buffer-shared-FBO defect class unrepresentable rather than
    // merely fixed.
    //
    // Target IS A ContentHash INPUT (the hash covers the whole record), and the emitter's
    // suppressor must be keyed by the framebuffer the record names, not by one global slot:
    // two different objects' Named records in a row must both go out, and a Named record must
    // never be suppressed against the same object's bound record or the reverse.
    enum class MGPipeFramebufferTarget : Uint8 {
        Draw = 0,
        Read = 1,
        Both = 2,
        // Describes the framebuffer named by Fbo and changes no binding (ID-19). Emitted
        // ahead of every DSA entry point that hands that framebuffer over by name.
        Named = 3,
        Count,
    };

    // MGPFramebufferState::Color[] and DrawBuffers[] are ONE array width, and it is the wire's
    // bound rather than the driver's: GetDynamicParameters().MaxColorAttachments is the raw ES
    // cap and is not clamped to 8 on the GLES path, so a driver reporting more would silently
    // truncate this record. The framebuffer subsystem bit is REFUSED at its first lookup in
    // that case, with one ERROR naming the cap, and the legacy arm runs - the same shape the
    // backend's existing bit-8-requires-bit-7 refusal already ships
    // (ResolveFramebufferSubsystemArm, beside ResolveResourceSubsystemArm). Widening the
    // payload is a wire change nobody has evidence for, and truncating silently is the bug
    // class this phase is closing.
    inline constexpr Uint32 kMGPipeMaxColorAttachments = 8;
    static_assert(kMGPipeMaxColorAttachments == MobileGL::kMGMaxDrawBuffers,
                  "MGPFramebufferState::Color[] and DrawBuffers[] are one array width");

    // ONE RECORD DESCRIBES ONE FRAMEBUFFER OBJECT - the one named by Fbo - and Target says
    // whether it also moves a binding (P4a, D-C2 as corrected by ID-19; see
    // MGPipeFramebufferTarget above for the failure that forced it).
    //
    // A Named record describes that object and changes NO binding. Draw / Read / Both records
    // describe that object AND set the bound handle(s) of the target(s) they name. The applier
    // keeps these records PER FRAMEBUFFER OBJECT, keyed by Fbo's slot (generation checked on
    // lookup; a framebuffer has no wire lifetime - D-I2 - so a successor's record simply
    // overwrites the slot), plus the two bound handles; every DSA entry point that hands a
    // framebuffer to the server by name is preceded by a Named record.
    //
    // WHAT Target CHANGES, FIELD BY FIELD. NO FIELD IN THIS RECORD REFERS TO "the currently
    // bound framebuffer" - every one of them describes the object named by Fbo - and that is
    // the invariant a reader depends on:
    //
    //   Fbo, Color[], Depth, Stencil, ReadSurface, Width/Height/Layers/Samples,
    //   FixedSampleLocations, IsDefault, Complete
    //       properties of the object named by Fbo, identical in meaning under every Target.
    //       In particular ReadSurface is resolved from THAT framebuffer's own read buffer -
    //       on a Named record too - never from whichever framebuffer is bound to GL_READ.
    //   DrawBuffers[]
    //       a property of the named object; it reaches the driver's bound draw framebuffer
    //       only when Target is Draw or Both. Under Named it is stored with the object and
    //       applied when that object is next configured.
    //   Target
    //       the only binding-specific field: Draw/Read/Both name the binding(s) this record
    //       also sets, Named names none. It is a ContentHash input.
    //   ContentHash
    //       per RECORD, not per object, and the emitter's suppressor is keyed by the
    //       framebuffer named: a Named record must never be suppressed against the same
    //       object's bound record, nor one object's Named record against another's.
    struct MGPFramebufferState {
        MGPipeHandle Fbo; // kMGPipeDefaultFramebuffer for the default framebuffer
        MGPSurface Color[8];
        MGPSurface Depth, Stencil;
        // The RESOLVED read surface, not an index, and it is THIS framebuffer's own read
        // buffer under every Target - Named included. This is what structurally closes the
        // read-buffer-shared-FBO defect class.
        MGPSurface ReadSurface;
        // attachment index, -1 = NONE. The named object's array; applied to the bound draw
        // framebuffer only when Target is Draw or Both.
        Int8 DrawBuffers[8];
        Uint16 Width, Height, Layers, Samples;
        // Complete is FramebufferObject::CheckCompleteness(), the frontend-only answer - NOT
        // glCheckFramebufferStatus's. CheckFramebufferStatus_State additionally consults
        // ActiveBackendRejectsDistinctDepthStencil() and HasNonRenderableColorAttachment,
        // which read the backend's probed format-capability cache; a client emitting that
        // answer would be reading the backend from the client side, which is the exact
        // coupling this boundary exists to remove. A later phase must not assume the stronger
        // answer, and glCheckFramebufferStatus keeps answering from the frontend as it does
        // today.
        Uint8 FixedSampleLocations, IsDefault, Complete;
        // MGPipeFramebufferTarget, above (P4a, D-C2; was Pad0). Draw/Read/Both also set the
        // named binding(s); Named sets none (ID-19). The ONLY binding-specific field.
        Uint8 Target;
        Uint32 Pad1;
        // Two jobs (section 4.5.6): the server's render-pass memo key, and the CLIENT's
        // emission suppressor - an unchanged hash means this record is not sent at all.
        // The same pattern is mandatory for every kVarTail set_* below, or 26.2's
        // redundant glBindSampler traffic reappears as a variable-length record per batch.
        // Target is one of its inputs, and the suppressor is keyed per framebuffer.
        Uint64 ContentHash;
    };
    MGP_ASSERT_POD(MGPFramebufferState, 304);

    // GL_MAX_VERTEX_ATTRIBS as MobileGL advertises it, on the MG_Pipe side of the boundary.
    // It bounds the two declared counts of MGPVertexElements, the applier's two per-CSO
    // arrays and the vertex-buffer set. It MUST equal VertexArrayObject::MAX_VERTEX_ATTRIBS;
    // MG_Impl/Pipe/PipeFill.cpp is the one translation unit that sees both and carries the
    // static_assert, because this header may not include a frontend one.
    inline constexpr Uint32 kMGPipeMaxVertexAttribs = 32;

    // P4a, D-G2. MobileGL's texture-unit space is ONE MERGED array of
    // TextureState::MAX_TEXTURE_IMAGE_UNITS = 192 - there is no stage dimension on
    // set_sampler_views / bind_sampler_states / set_shader_images, because the same unit may
    // be sampled from two stages and per-stage 32 is an advertised number rather than a
    // storage shape. These two bound the three var-tail sets' Start + Count, and a record
    // that names a window outside them is Fatal{ProtocolCorruption} - the var-tail window IS
    // the bound and entries outside it are not cleared.
    //
    // Pinned against the frontend constant in MG_Impl/Pipe/PipeFill.cpp, the one translation
    // unit that sees both, exactly as kMGPipeMaxVertexAttribs is: this header may not include
    // a frontend one.
    inline constexpr Uint32 kMGPipeMaxTextureUnits = 192;
    inline constexpr Uint32 kMGPipeMaxImageUnits = 192;

    struct MGPVertexBuffer {
        MGPipeHandle Res;
        Uint64 Offset;
        Uint32 Stride;
        Uint32 Divisor;
        Uint32 BindingIndex;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPVertexBuffer, 32);

    // Var-tail header: MGPVertexBuffer[Count] follows.
    struct MGPVertexBuffers {
        Uint32 Start, Count;
        // The vertex-FETCH base instance these offsets are valid for (P3a, D-H1). It is DRAW
        // state, not VAO state, and it is NOT the same thing as MGPDrawInfo::StartInstance:
        // that one is the GL draw's baseInstance and feeds gl_BaseInstance, this one is the
        // shift the fetch address of an instanced array needs when the device has no native
        // base-instance support. The server decides whether to emulate it or let
        // GL_EXT_base_instance do the work - emulation is server-owned - so the client sends
        // the draw's raw value and never a pre-shifted offset.
        //
        // IT IS A ContentHash INPUT, and that is a requirement rather than a nicety:
        // set_vertex_buffers is suppressed on an unchanged hash (MG_Impl/Pipe/
        // SetHashSuppressor.h's SetVertexBuffers slot), so a baseInstance that moved while
        // the buffer set did not would be suppressed and the server would keep the previous
        // shift. It rides ONE PER EMITTED SET rather than per entry: per entry the shift is
        // redundant and lets a malformed record disagree with itself.
        Uint32 BaseInstance;
        Uint32 Pad0;
        Uint64 ContentHash;
    };
    MGP_ASSERT_POD(MGPVertexBuffers, 24);

    // An independent call, NOT a subset of the VAO configuration version (D5).
    struct MGPIndexBuffer {
        MGPipeHandle Res;
        Uint64 Offset;
        Uint32 IndexSize;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPIndexBuffer, 24);

    struct MGPIndirectBuffers {
        MGPipeHandle DrawIndirect;
        MGPipeHandle Parameter;
    };
    MGP_ASSERT_POD(MGPIndirectBuffers, 16);

    // One entry of set_sampler_views. No stage dimension: MobileGL's texture unit space is
    // MERGED (TextureState::m_textureUnits is one Array of MAX_TEXTURE_IMAGE_UNITS = 192),
    // and the same unit may be sampled from two stages (section 4.4.3).
    struct MGPBoundView {
        MGPipeHandle View;
        MGPipeHandle Texture;
        Uint32 Unit;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPBoundView, 24);

    struct MGPSamplerViews {
        Uint32 Start, Count;
        Uint64 ContentHash;
    };
    MGP_ASSERT_POD(MGPSamplerViews, 16);

    // Var-tail header: MGPipeHandle[Count] of sampler CSOs follows.
    struct MGPSamplerStates {
        Uint32 Start, Count;
        Uint64 ContentHash;
    };
    MGP_ASSERT_POD(MGPSamplerStates, 16);

    struct MGPImageView {
        MGPipeHandle Res;
        Uint32 Unit;
        Uint32 InternalFormat;
        Uint32 Layer;
        Uint16 Level;
        Uint8 Layered;
        Uint8 Access;
    };
    MGP_ASSERT_POD(MGPImageView, 24);

    struct MGPShaderImages {
        Uint32 Start, Count;
        Uint64 ContentHash;
    };
    MGP_ASSERT_POD(MGPShaderImages, 16);

    // One bound buffer range: 24 bytes, no inline host span. The named-UBO host bytes a
    // backend needs under kCapNeedsHostUboBytes (D-B8) travel as an OPTIONAL second var-tail,
    // MGHostSpan[HostSpanCount] behind the ranges, announced by MGPShaderBuffers below. An
    // inline span would have cost every SSBO, atomic-counter and XFB range 32 dead bytes, and
    // D-B8 says not to freeze that payload's shape before the stage-ubo-named counter has
    // produced numbers.
    struct MGPBufferRange {
        MGPipeHandle Res;
        Uint64 Offset;
        Uint64 Size;
    };
    MGP_ASSERT_POD(MGPBufferRange, 24);

    // Var-tail header: MGPBufferRange[Count], then MGHostSpan[HostSpanCount]. HostSpanCount is
    // 0, or Count for the Uniform class under kCapNeedsHostUboBytes (a range with nothing to
    // ship carries an empty span, so the two arrays stay index-aligned).
    struct MGPShaderBuffers {
        Uint32 Class; // Uniform | ShaderStorage | AtomicCounter
        Uint32 Start;
        Uint32 Count;
        Uint32 WritableMask;
        Uint32 HostSpanCount; // 0, or Count when the kHostSpan tail is present (D-B8)
        Uint32 Pad0;
        Uint64 ContentHash;
    };
    MGP_ASSERT_POD(MGPShaderBuffers, 32);

    // Var-tail header: MGPBufferRange[Count] then Uint32 offsets[Count].
    struct MGPStreamOutputTargets {
        Uint32 Count;
        Uint32 Pad0;
        Uint64 Generation;
        Uint64 ContentHash;
    };
    MGP_ASSERT_POD(MGPStreamOutputTargets, 24);

    // Covers the DEFAULT UNIFORM BLOCK only (D6).
    struct MGPGlobalConstants {
        MGPipeHandle ShaderCso;
        Uint32 Version;
        Uint32 Pad0;
        MGPBlobRef Blob;
    };
    MGP_ASSERT_POD(MGPGlobalConstants, 40);

    // The float/int/uint view is resolved on the CLIENT by ClassifyVertexAttribType.
    struct MGPAttribValue {
        Uint32 Location;
        Uint8 ValueClass; // Float | Int | Uint | Double
        Uint8 Pad0[3];
        Uint32 Data[4];
    };
    MGP_ASSERT_POD(MGPAttribValue, 24);

    // Var-tail header: MGPAttribValue[popcount(Mask)] follows.
    struct MGPVertexAttribDefaults {
        Uint32 Mask;
        Uint32 Count;
    };
    MGP_ASSERT_POD(MGPVertexAttribDefaults, 8);

    // PACK only. There is deliberately no unpack counterpart: nothing on the far side of
    // the boundary reads unpack state (section 4.6 D5), and the staged-repack upload path
    // does not even issue glPixelStorei.
    struct MGPPixelPackState {
        PixelStoreParameters Pack;
    };
    static_assert(std::is_trivially_copyable_v<MGPPixelPackState>);
    // 28 is what PixelStoreParameters measures: two Bools, two bytes of padding, six Ints.
    // Asserting against sizeof(PixelStoreParameters) itself was a tautology that could not
    // notice the value struct changing width under the wire format.
    static_assert(sizeof(MGPPixelPackState) == 28,
                  "MGPPixelPackState changed size; update the wire format and this assertion");

    // Also a shader-variant input: both backends bake these into the synthesized
    // pass-through control stage.
    struct MGPPatchState {
        Uint32 Vertices;
        Uint32 Pad0;
        Float Outer[4];
        Float Inner[2];
        Uint32 Pad1[2];
    };
    MGP_ASSERT_POD(MGPPatchState, 40);

    // Migration-only (section 6.3). Every stage removes fields and lowers
    // MGL_RESIDUAL_BLOCK_SIZE; P13 asserts it is zero, which is the retirement trip wire.
    //
    // Layout must be asserted MEMBER BY MEMBER, not only by sizeof: a heterogeneous POD
    // union is where padding differs across ABIs, and the monolith verify harness is blind
    // to it because both sides are the same translation unit. G3 emits the offsetof
    // assertions; under split the block is serialized field-wise rather than memcpy'd.
    struct ResidualValueBlock {
        // The 35 CapabilityInput bits, packed in enum order. P2 retired everything else:
        // RenderStateParameters to create/bind_render_state + set_dynamic_state, Pack to
        // set_pixel_pack_state, and the patch quintet to set_patch_state.
        //
        // What is left is deliberately REDUNDANT. Every one of the 35 capabilities is
        // answerable from the assembled working block now that P2 gave FramebufferSrgb,
        // DepthClamp and TextureCubeMapSeamless real storage - which is the point: the
        // applier compares the two answers bit by bit, so the day a later call takes a
        // capability over and forgets to carry it, the block says so on the next draw
        // (Fatal{PipeResidualDiverged, "<Cap>"}, MG_Pipe/PipeApply.cpp).
        Uint64 CapabilityBits;
    };
    static_assert(std::is_trivially_copyable_v<ResidualValueBlock>);
// The retirement ratchet. This number only ever goes DOWN: every stage that lands a real
// set_* call deletes fields here and lowers it, and P13 replaces it with
// static_assert(sizeof(ResidualValueBlock) == 0), which stays red until the last field is
// gone. Shrinking the block without lowering the number, or growing it at all, is a build
// break - which is the point.
//
// Stable across the ABIs MobileGL ships on: the one member is a fixed-width scalar.
//
// P2: 1248 -> 8. RenderStateParameters (1168) retired to create/bind_render_state and
// set_dynamic_state, PixelStoreParameters (28) to set_pixel_pack_state, and the patch
// quintet (52 with its padding) to set_patch_state.
#define MGL_RESIDUAL_BLOCK_SIZE 8
    static_assert(sizeof(ResidualValueBlock) == MGL_RESIDUAL_BLOCK_SIZE,
                  "the residual value block changed size; lower MGL_RESIDUAL_BLOCK_SIZE if a field "
                  "retired, and do not raise it");

    struct MGPResidualValueState {
        Uint32 Version;
        Uint32 Pad0;
        MGPBlobRef Blob;
    };
    MGP_ASSERT_POD(MGPResidualValueState, 32);

    // ---------------------------------------------------------------------------------
    // Transfer
    // ---------------------------------------------------------------------------------

    // Shape copied from the unpack ring's existing UnpackStagingBlock. The source strides
    // are CARRIED, not inferred from a pointer comparison: the old
    // `uploadData == mipData` test cannot survive a split, where the client neither ships
    // the whole level nor keeps a server-side mirror of it (section 4.5.6).
    struct MGPSubRegion {
        Int32 X, Y, Z;
        Uint32 W, H, D;
        Uint64 SrcOffset;      // into the blob
        Uint32 SrcRowStride;   // bytes; 0 = tightly packed (w * bpp)
        Uint32 SrcSliceStride; // bytes; 0 = tightly packed
    };
    MGP_ASSERT_POD(MGPSubRegion, 40);

    // Carries the union box AND the region list so the SERVER picks the upload shape - the
    // decision belongs on the side that pays the GPU cost. Mali prices texture upload by
    // JOB COUNT: ~100 sprite rects against one union box measured +6 ms/frame.
    //
    // `Target` IS TWO FACTS IN ONE Uint16 (P4a, D-D3 / ID-12), and MGPipePackSubDataTarget
    // under the struct is the only spelling of the encoding - nothing may open-code a half:
    //
    //   low byte  = MGPipeResourceTarget          - WHICH KIND of storage the destination is.
    //                                               The applier branches on it: a buffer
    //                                               target dispatches into MGPipeResourceOps,
    //                                               every other target accumulates a pending
    //                                               upload for the texture sync to consume.
    //   high byte = MobileGL::TextureUploadTarget - WHICH cube face / upload target the level
    //                                               belongs to. It is NOT derivable from the
    //                                               resource target - six faces share TexCube
    //                                               - and 26 enumerators leave a byte ample.
    //
    // WHY THAT WAY ROUND, AND WHY THE ENCODING LIVES HERE RATHER THAN IN EACH EMITTER. The
    // applier's SubDataNamesABuffer tests the WHOLE field == 0, and
    // TextureUploadTarget::Texture1D is 0 - so a texture record carrying the bare upload
    // enumerator is indistinguishable from a buffer record exactly when its owner is a 1D
    // texture, and that texture's upload is dispatched into the buffer path. With the
    // resource target in the LOW byte a buffer record's Target stays EXACTLY
    // kMGPipeResourceTargetBuffer - P3a's buffer records are unchanged on the wire, their
    // upload byte being zero too - while a texture record can never be zero, because no
    // texture's MGPipeResourceTarget is. The static_assert under the struct holds that
    // invariant, and the applier's whole-field test stays right either way.
    //
    // THE BUFFER HALF. With Target == Buffer there is no level and no box, so the destination
    // byte range rides in the box's first coordinate and first extent: UnionBox.X is the byte
    // offset, UnionBox.W the byte size, Y = Z = 0, H = D = 1, Level = 0, RegionCount = 0.
    //
    // THE BLOB RULE, THE SAME ONE MGPVertexElements ABOVE CARRIES: `Blob.Size` is the record's
    // own statement of how many bytes its blob holds and the applier holds the record to that
    // statement whenever the record makes it - a non-zero Blob.Size that is not exactly the
    // record's own byte size (MGPipeSubDataBufferSize below) is Fatal{ProtocolCorruption} and
    // the write is refused. A zero Blob.Size means "this record does not declare its blob",
    // which is what a monolith emission is: the bytes travel beside the record through
    // MGPipeApplyResourceSubData's companion `const void*`. The destination range is what
    // bounds the write in both cases. That caps ONE record at a 2^31-1 offset and a
    // 2^32-1 size; a range beyond either is split by the emitter - the same rule, and at
    // SEG_STAGE's 32 MiB the far tighter one, that the ring's half-capacity bound already
    // imposes on it. MGPipeSetSubDataBufferRange / MGPipeSubDataBufferOffset / Size below are
    // the only spelling of this convention; nothing else reads the box for a buffer.
    struct MGPSubData {
        MGPipeHandle Res;
        // Target is PACKED - see the block above, and read it only through
        // MGPipeSubDataResourceTargetOf / MGPipeSubDataUploadTargetOf below.
        Uint16 Target, Level;
        // Replaces the backend's `uploadData == mipData` pointer comparison: are these
        // bytes an untransformed level shadow?
        Uint8 SourceIsVerbatimLevelShadow;
        Uint8 Pad0[3];
        MGPBox UnionBox;
        Uint32 RegionCount; // MGPSubRegion[] in the variable tail
        Uint32 Pad1;
        MGPBlobRef Blob;
    };
    MGP_ASSERT_POD(MGPSubData, 72);

    // The one spelling of MGPSubData::Target's encoding, stated above the struct.
    //
    // Uint32 ARGUMENTS RATHER THAN THE TWO ENUM TYPES, and that is deliberate. This header is
    // the contract: MGPipeResourceTarget is minted in it, but the upload half is MG_State's
    // TextureUploadTarget, and nobody who reads the packed field ever needs that type - the
    // applier and both backends read the halves BACK, as bytes, through the two accessors.
    // Naming it in a signature would pin the contract's own API to a frontend enum for no
    // reader's benefit, and would stop kMGPipeResourceTargetBuffer being passed as it stands.
    // Callers pass static_cast<Uint32>(MobileGL::TextureUploadTarget) for `uploadTarget` and
    // static_cast<Uint32>(MGPipeResourceTarget) - or kMGPipeResourceTargetBuffer - for
    // `resourceTarget`.
    constexpr inline Uint16 MGPipePackSubDataTarget(Uint32 resourceTarget, Uint32 uploadTarget) {
        return static_cast<Uint16>((resourceTarget & 0xFFu) | ((uploadTarget & 0xFFu) << 8));
    }
    // Comparable against static_cast<Uint8>(MGPipeResourceTarget) / kMGPipeResourceTargetBuffer.
    constexpr inline Uint8 MGPipeSubDataResourceTargetOf(Uint16 packed) {
        return static_cast<Uint8>(packed & 0xFFu);
    }
    // Comparable against static_cast<Uint8>(MobileGL::TextureUploadTarget).
    constexpr inline Uint8 MGPipeSubDataUploadTargetOf(Uint16 packed) {
        return static_cast<Uint8>((packed >> 8) & 0xFFu);
    }
    // THE INVARIANT P3a's records and the applier's buffer test both rest on: a buffer
    // record's Target is exactly kMGPipeResourceTargetBuffer, whole field, upload byte and
    // all. TextureUploadTarget::Texture1D is 0, so the buffer case is the one place where the
    // packed form and a bare enumerator agree - and it has to stay that place.
    static_assert(MGPipePackSubDataTarget(kMGPipeResourceTargetBuffer, 0u) ==
                      kMGPipeResourceTargetBuffer,
                  "a buffer sub-data record's Target must stay exactly "
                  "kMGPipeResourceTargetBuffer: the applier's SubDataNamesABuffer tests the "
                  "whole field == 0");

    // Encodes a buffer byte range into the record's box. False, with the record untouched,
    // when the range does not fit one record: the emitter has to split it.
    inline Bool MGPipeSetSubDataBufferRange(MGPSubData& record, Uint64 offset, Uint64 size) {
        if (offset > 0x7FFFFFFFull || size > 0xFFFFFFFFull) {
            return false;
        }
        record.UnionBox = MGPBox{static_cast<Int32>(offset), 0, 0, static_cast<Uint32>(size), 1, 1};
        record.Level = 0;
        record.RegionCount = 0;
        return true;
    }
    inline Uint64 MGPipeSubDataBufferOffset(const MGPSubData& record) {
        // A negative X is a corrupt record (the encoder never writes one); read as unsigned
        // it lands above the encodable bound, which the applier's bounds gate refuses.
        return static_cast<Uint64>(static_cast<Uint32>(record.UnionBox.X));
    }
    inline Uint64 MGPipeSubDataBufferSize(const MGPSubData& record) { return record.UnionBox.W; }

    // P3a, D-A5: the per-record half of resource_respecify's kNeedsAck.
    //
    // Flags are a PER-CALL static property and resource_respecify serves BOTH glBufferData
    // and glBufferStorage. A bare kNeedsAck on the call would acknowledge every glBufferData
    // in a world upload; only glBufferStorage is a real synchronous allocation and only it is
    // allowed a synchronous ack. So kNeedsAck on the call means "records of this call MAY
    // require an acknowledgement" and THIS predicate decides per record. In monolith the ack
    // is ((void)0) - the applier is one function call away - and the transport wires the
    // doorbell to this predicate when it lands.
    //
    // P4a, D-A2: THE PREDICATE IS NARROWED TO NAME THE BUFFER TARGET, and that is a
    // requirement rather than a tidy-up. glTexStorage* also sets Immutable - it is a real
    // descriptor fact the backend reads, and the client must set it - but texture allocation
    // is already deferred to sync time in monolith (glTexImage*/glTexStorage* only
    // MarkStorageDirty; even glRenderbufferStorage* allocates lazily inside SyncToBackend), so
    // splitting changes no observable behaviour and this batch must NOT ack. glBufferStorage
    // stays the only entry point allowed a synchronous acknowledgement.
    //
    // PipeCatalogueTest.ResourceRespecifyAcksOnlyImmutableStorage drives glTexStorage2D and
    // glRenderbufferStorage idioms through it, and is the negative control for a future
    // widening.
    inline Bool MGPipeResourceRespecifyNeedsAck(const MGPResourceDesc& desc) {
        return desc.Immutable != 0 && desc.Target == kMGPipeResourceTargetBuffer;
    }

    // P4a, ID-18 M4: A RESPECIFY WHOSE STORAGE-DEFINING FIELDS ALL EQUAL THE STORED
    // DESCRIPTOR IS A METADATA UPDATE, NOT A REALLOCATION.
    //
    // MGPResourceDesc::BindMask and ImageBindableHint are STICKY facts the client discovers
    // AFTER allocation - a texture first bound as a shader image, first used as a render
    // target - and they ride resource_create and every resource_respecify. An IMMUTABLE
    // texture never has a later respecify, so without a rule those two would reach the server
    // only by accident, or never; with one, a mask change after allocation emits a
    // resource_respecify that REPEATS the storage the resource already has.
    //
    // The applier and both twins must classify such a record as a metadata update:
    //   - NO reallocation acknowledgement. MGPipeResourceRespecifyNeedsAck above still
    //     answers the per-record question, but a metadata update allocates nothing, so a
    //     record it classifies as metadata is not acked even when that predicate says the
    //     call may require one.
    //   - NO PendingUploads clear when the call names NO level. This REFINES the whole-resource
    //     clear: identical storage fields with a null MGPRespecifiedLevel clear NOTHING. (The
    //     level-scoped rule exists because clearing the whole vector on a level-1 definition
    //     silently dropped level 0's accepted texels; a metadata update must drop neither.) A
    //     call that NAMES a level is that level's redefinition whatever the descriptor says -
    //     a non-base level's extent is not a descriptor field - and drops exactly that level
    //     (P4a final review C-1); the client's mask republish passes null on purpose.
    //   - The stored descriptor's BindMask and ImageBindableHint ARE updated: the applier
    //     replaces the descriptor WHOLE with the one the client sent (PipeApply.cpp), and the
    //     mask in it is the CLIENT's sticky OR (TextureEmit.h's entry, never cleared), so the
    //     replacement can never lose a bit the record once carried. The twin re-derives its
    //     storage flags from the new mask on its next sync, recreating backend storage only
    //     where the backend actually needs it. The record itself is not a request to recreate.
    //
    // THE STORAGE-DEFINING FIELD SET, named here so that neither side has to guess and a
    // later field cannot join it by silence. It is every MGPResourceDesc member except the
    // three metadata ones and the padding:
    //
    //     Target, StorageKind, InternalFormat, Width, Height, Depth, ArrayLayers, Levels,
    //     Samples, FixedSampleLocations, Immutable, Usage, StorageFlags, HasDefinedContent,
    //     ViewOf, BufferForTexBuffer, BufOffset, BufSize.
    //
    // `Resource` is the identity the stored descriptor is looked up BY, not a comparand. The
    // three fields that may differ on a metadata update are exactly BindMask,
    // ImageBindableHint and GlNameForDiag (diagnostics only, never an identity, never a memo
    // key). HasDefinedContent is storage-defining ON PURPOSE: glBufferData(size, NULL) at an
    // unchanged size is an orphaning reallocation and has to keep clearing, rather than being
    // mistaken for a mask change. A field added to MGPResourceDesc must be placed in one of
    // the two lists in the same commit - PipeCatalogue pins the struct's size for that.

    // The forward terminator for a server-initiated texture pull (section 7.1). May carry
    // zero regions - that is how a pull that needs nothing is answered.
    struct MGPSubDataComplete {
        MGPipeHandle Res;
        Uint16 Target, FirstLevel, LevelCount, Pad0;
        Uint64 PullSerial;
    };
    MGP_ASSERT_POD(MGPSubDataComplete, 24);

    // Carries the application's REAL access flags, not a normalized subset.
    struct MGPFlushRange {
        MGPipeHandle Res;
        Uint64 Offset, Size;
        Uint32 AccessFlags; // Flags<BufferMappingAccessBit>
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPFlushRange, 32);

    struct MGPReadback {
        MGPipeHandle Res;
        Uint64 Offset, Size;
    };
    MGP_ASSERT_POD(MGPReadback, 24);

    struct MGPCopyRegion {
        MGPipeHandle Src, Dst;
        MGPBox SrcBox;
        Int32 DstX, DstY, DstZ;
        Uint16 SrcTarget, DstTarget;
        Uint16 SrcLevel, DstLevel;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPCopyRegion, 64);

    struct MGPBlit {
        MGPipeHandle ReadFbo, DrawFbo;
        Int32 SrcX0, SrcY0, SrcX1, SrcY1;
        Int32 DstX0, DstY0, DstX1, DstY1;
        Uint32 Mask;
        Uint32 Filter;
    };
    MGP_ASSERT_POD(MGPBlit, 56);

    // One discriminated record replacing glClear, the four glClearBuffer* and the four
    // glClearNamedFramebuffer* entry points (section 4.4.4).
    struct MGPClear {
        MGPipeHandle Fbo;
        Uint32 Kind;   // Whole | Color | Depth | Stencil | DepthStencil
        Int32 DrawBufferIndex;
        Uint32 BufferMask; // GL_COLOR_BUFFER_BIT etc. for the whole-framebuffer form
        Uint32 ValueClass; // Float | Int | Uint
        Uint32 ColorValue[4];
        Float DepthValue;
        Int32 StencilValue;
    };
    MGP_ASSERT_POD(MGPClear, 48);

    struct MGPMipPlan {
        MGPipeHandle Res;
        Uint16 Target, BaseLevel, LevelCount, Pad0;
    };
    MGP_ASSERT_POD(MGPMipPlan, 16);

    // read_pixels and get_texture_image share one shape; both answer into a reply slot.
    struct MGPReadbackInfo {
        MGPipeHandle Res; // null for read_pixels: the bound read surface answers
        MGPBox Box;
        Uint32 Format, Type;
        Uint16 Target, Level;
        Uint32 Pad0;
        Uint64 DstOffset, DstSize;
    };
    MGP_ASSERT_POD(MGPReadbackInfo, 64);

    // ---------------------------------------------------------------------------------
    // Commands
    // ---------------------------------------------------------------------------------

    enum MGPDrawFlagBit : Uint8 {
        kDrawHasUserIndices = 1u << 0,
        kDrawPrimitiveRestart = 1u << 1,
        kDrawIndicesAreClient = 1u << 2,
        kDrawHasIndexRange = 1u << 3,
        kDrawHasXfbCount = 1u << 4,
    };

    // = pipe_draw_info. Today's twenty draw entry points collapse onto this one call, with
    // MGPDrawRange[] holding exactly the shape the glMultiDraw* family already has.
    //
    // minIndex/maxIndex are computed only on the client-memory array path today, and
    // xfbCpuCapturedVertices only on the XFB scatter path, so Flags gates the WORK. They
    // stay in the fixed head; moving them into the variable tail is a wire-format decision
    // that belongs with the transport (P5), where per-draw byte histograms exist to size
    // it. userIndices is in the variable tail already, so the VBO path - every Minecraft
    // and Sodium draw - never pays the 32 bytes of an MGHostSpan.
    struct MGPDrawInfo {
        Uint32 Mode;
        Uint8 IndexSize; // 0 = arrays, else 1 / 2 / 4
        Uint8 Flags;     // MGPDrawFlagBit
        Uint16 Pad0;
        Uint32 InstanceCount, StartInstance;
        Uint32 RestartIndex;
        Uint32 DrawIdOffset;
        MGPipeHandle IndexResource;
        Uint32 MinIndex, MaxIndex; // ~0 = unknown
        Uint64 XfbCpuCapturedVertices;
        Uint32 NumDraws; // MGPDrawRange[] in the variable tail
        Uint32 Pad1;
    };
    MGP_ASSERT_POD(MGPDrawInfo, 56);

    // = pipe_draw_start_count_bias.
    struct MGPDrawRange {
        Uint32 Start, Count;
        Int32 IndexBias;
    };
    MGP_ASSERT_POD(MGPDrawRange, 12);

    // Present when the draw is indirect. The client resolves the COUNT itself, so the
    // server never reads an indirect command block to learn how many draws there are.
    struct MGPDrawIndirect {
        MGPipeHandle Buffer;
        MGPipeHandle ParameterBuffer;
        Uint64 Offset, ParameterOffset;
        Uint32 Stride, DrawCount;
    };
    MGP_ASSERT_POD(MGPDrawIndirect, 40);

    struct MGPGridInfo {
        Uint32 GridX, GridY, GridZ;
        Uint32 BlockX, BlockY, BlockZ;
        MGPipeHandle IndirectBuffer;
        Uint64 IndirectOffset;
        Uint8 IsIndirect;
        Uint8 Pad0[7];
    };
    MGP_ASSERT_POD(MGPGridInfo, 48);

    struct MGPMemoryBarrier {
        Uint32 Bits; // GLbitfield
        Uint8 ByRegion;
        Uint8 Pad0[3];
    };
    MGP_ASSERT_POD(MGPMemoryBarrier, 8);

    struct MGPStreamOutputBegin {
        Uint32 PrimitiveMode;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPStreamOutputBegin, 8);

    // end_stream_output carries the accounting the client owns; the scatter itself is a
    // read-modify-write of the client's shadow and lives there (section 7.2.1).
    struct MGPXfbAccounting {
        Uint64 CapturedVertices;
        Uint64 PrimitivesWritten;
        Uint32 PrimitiveMode;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPXfbAccounting, 24);

    struct MGPStreamOutputControl {
        Uint32 Reserved;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPStreamOutputControl, 8);

    struct MGPFlush {
        Uint32 Flags;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPFlush, 8);

    struct MGPPresent {
        Uint64 FrameSerial;
    };
    MGP_ASSERT_POD(MGPPresent, 8);

    struct MGPSwapInterval {
        Int32 Interval;
        Uint32 Pad0;
    };
    MGP_ASSERT_POD(MGPSwapInterval, 8);

    // ---------------------------------------------------------------------------------
    // Reverse channel payloads (section 7.1)
    // ---------------------------------------------------------------------------------

    struct MGPSurfaceInfo {
        Uint32 Width, Height;
        Uint32 InternalFormat;
        Uint16 Samples, Layers;
        Uint8 IsDefault;
        Uint8 Pad0[7];
    };
    MGP_ASSERT_POD(MGPSurfaceInfo, 24);

#undef MGP_ASSERT_POD
} // namespace MobileGL::MG_Pipe
